# -*- coding: utf-8 -*-
"""SAC AIRPORT CATCHMENT_Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fgwkm2GsPn5VqZvyGKZy4LcUeegsIHx_
"""

# importing libraries

import pandas as pd
import geopandas as gpd
import requests
import folium
import json
import time
import os

# configuration

ORS_API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjE2YzYyMzI0OWZlYzRiNzJiYjI2MDAzZmRlZmY4ZjRiIiwiaCI6Im11cm11cjY0In0="

# airport definitions

AIRPORTS = [
    {'name': 'Heathrow Airport',
     'iata': 'LHR',
     'lat': 51.4700,
     'lon': -0.4543,
     'colour': 'blue'},
    {'name': 'Gatwick Airport',
     'iata': 'LGW',
     'lat': 51.1537,
     'lon': -0.1821,
     'colour': 'green'},
    {'name': 'Luton Airport',
     'iata': 'LTN',
     'lat': 51.8747,
     'lon': -0.3683,
     'colour': 'red'}
]

# isochrone time bands
TIME_BANDS = [1800, 2700, 3600]
TIME_LABELS = ['30 min', '45 min', '60 min']

print(f' Airports: {[a["iata"] for a in AIRPORTS]}')
print(f' Time bands: {TIME_BANDS}')

airport_lookup = {a['iata']: a for a in AIRPORTS}
print(f' Airport lookup ready')

from prompt_toolkit import key_binding
from IPython.core.shellapp import SYSTEM_CONFIG_DIRS
# testing API connection on Luton airport

def get_isochrones(lon, lat, time_bands, api_key):
    url = 'https://api.openrouteservice.org/v2/isochrones/driving-car'

    headers = {
        'Authorization': api_key,
        'Content-Type': 'application/json'
    }

    body = {
        'locations': [[lon, lat]],
        'range': time_bands,
        'range_type': 'time'
    }

    response = requests.post(url, json=body, headers=headers)

    if response.status_code == 200:
        return response.json()
    else:
        print(f' API error {response.status_code}: {response.text}')
        return None

# Test with Luton

test_airport = AIRPORTS[2]
print(f' Testing connection with {test_airport["name"]}...')

test_result = get_isochrones(
    lon=test_airport['lon'],
    lat=test_airport['lat'],
    time_bands=TIME_BANDS,
    api_key=ORS_API_KEY
)

if test_result:
    print(f' Received {len(test_result["features"])} zones for {test_airport["name"]}')
else:
    print('Error - check API key')

"""Run test was good, now generating for all three airports"""

# generating isocrhones for all airports

all_isochrones = {}

for airport in AIRPORTS:
    print(f'Generating isochrones for {airport["name"]} ({airport["iata"]})...')

    result = get_isochrones(
        lon=airport['lon'],
        lat=airport['lat'],
        time_bands=TIME_BANDS,
        api_key=ORS_API_KEY
    )

    if result:
        all_isochrones[airport['iata']] = result
        print(f' {airport["iata"]} - {len(result["features"])} received')
    else:
        print(f' {airport["iata"]} - failed')

    time.sleep(1)

print(f' {len(all_isochrones)}/{len(AIRPORTS)} all airports processed')

all_isochrones = {}
for iata in ['LHR', 'LGW', 'LTN']:
    path = f'/content/drive/MyDrive/catchment_data/{iata}_isochrones.geojson'
    with open(path, 'r') as f:
        all_isochrones[iata] = json.load(f)
    print(f' Loaded {iata}')

# map of all airports

map_centre = [51.5, -0.3]
map = folium.Map(location=map_centre, zoom_start=7, tiles='cartodbpositron')

opacities = [0.25, 0.15, 0.08]

airport_lookup = {a['iata']: a for a in AIRPORTS}

for iata, geojson in all_isochrones.items():
  airport = airport_lookup[iata]
  colour = airport['colour']
  name = airport['name']

  for i, feature in enumerate(geojson['features']):
    label = f"{airport['name']} - {TIME_LABELS[i]} drive"

    folium.GeoJson(
        feature,
        style_function= lambda x, c=colour, o=opacities[i]: {
            'fillColor': c,
            'fillOpacity': o,
            'color': c,
            'weight': 1.5
        },
        tooltip=label
    ).add_to(map)

#adding airport markers
for airport in AIRPORTS:
  if airport['iata'] in all_isochrones:
    folium.Marker(
        location=[airport['lat'], airport['lon']],
        tooltip=f"{airport['name']} ({airport['iata']})",
        icon=folium.Icon(color=airport['colour'], icon='plane', prefix='fa')
    ).add_to(map)

# adding a legend

legend_html = '''
<div style="position: fixed; bottom: 30px; left: 30px; z-index: 1000;
            background-color: white; padding: 12px 16px;
            border-radius: 8px; border: 1px solid #ccc;
            font-family: Arial; font-size: 13px; line-height: 1.8;">
  <b>Airport Catchment Areas</b><br>
  <span style="color:blue">■</span> Heathrow (LHR)<br>
  <span style="color:red">■</span> Gatwick (LGW)<br>
  <span style="color:green">■</span> Luton (LTN)<br>
  <hr style="margin:4px 0">
  Dark fill = 60 min drive<br>
  Medium fill = 90 min drive<br>
  Light fill = 120 min drive
</div>
'''
map.get_root().html.add_child(folium.Element(legend_html))

print('Map built')
print('Map displayed below: ')

map

# installing map library for boundary data

!pip install mapclassify

# working on the ITL3 boundaries from the ONS geoportal

itl3 = gpd.read_file("/content/International_Territorial_Level_3_(January_2021)_Boundaries_UK_BFC_(V4)_.zip")

print(f" Loaded {len(itl3)} ITL3 regions")
print(f" Columns: {list(itl3.columns)}")
print(f" CRS: {itl3.crs}")

"""had to use the shapefile as the geojson was corrupted or was missing data"""

# need to check the data first

print(itl3.head())
print(f' Coordinate system (CRS): {itl3.crs}')

if itl3.crs.to_epsg() !=4326:
  print('Converting CRS to WGS84 (EPSG:4326) ')
  itl3 = itl3.to_crs(epsg=4326)
  print('CRS converted')

else:
  print('CRS already WSG84 - no conversion was needed')

# spatial join - for each airport isocrhone i need to see under which ITL3 regions it will fall under

from shapely.geometry import shape

isochrone_rows = []

for iata, geojson in all_isochrones.items():
  airport = airport_lookup[iata]
  for i, feature in enumerate(geojson["features"]):
    isochrone_rows.append({
        "airport_name": airport["name"],
        "airport_iata": iata,
        "time_label": TIME_LABELS[i],
        "time_seconds": TIME_BANDS[i],
        "geometry": shape(feature["geometry"])
    })

isochrones_gdf = gpd.GeoDataFrame(isochrone_rows, crs="EPSG:4326")
print(f' Converted{len(isochrones_gdf)} isochrone features to a GeoDataFrame')

joined = gpd.sjoin(
    itl3,
    isochrones_gdf,
    how="inner",
    predicate="intersects"
)

print(f' Spatial join is complete')
print(f' Found {len(joined)} ITL3- isocrhone mathces \n')

# summary -> how many itl3 regions per airport and per time band

summary = (
    joined
    .groupby(["airport_iata", "time_label"])["ITL321NM"]
    .count()
    .reset_index()
    .rename(columns={"ITL321NM": "itl3_region_count"})
)

print('ITL3 regions within each catchment zone: ')
print(summary.to_string(index=False))

# visualising itl3 regions on the map
# building a layered map

# Centre map over London
m_combined = folium.Map(
    location=[51.5, -0.3],
    zoom_start=7,
    tiles="CartoDB positron"
)

# layer 1:ITL3 regions within catchment

matched_itl3_codes = joined["ITL321CD"].unique()
itl3_in_catchment  = itl3[itl3["ITL321CD"].isin(matched_itl3_codes)]

folium.GeoJson(
    itl3_in_catchment.__geo_interface__,
    name="ITL3 Regions",
    style_function=lambda x: {
        "fillColor":   "#ffff00",
        "color":       "#666666",
        "fillOpacity": 0.15,
        "weight":      1
    },
    tooltip=folium.GeoJsonTooltip(
        fields=["ITL321CD", "ITL321NM"],
        aliases=["ITL3 Code:", "ITL3 Region:"]
    )
).add_to(m_combined)

# layer 2:isochrone catchment zones

opacities = [0.25, 0.15, 0.08]

for iata, geojson in all_isochrones.items():
    airport = airport_lookup[iata]
    colour  = airport["colour"]
    for i, feature in enumerate(geojson["features"]):
        folium.GeoJson(
            feature,
            name=f"{airport['iata']} — {TIME_LABELS[i]}",
            style_function=lambda x, c=colour, o=opacities[i]: {
                "fillColor":   c,
                "color":       c,
                "fillOpacity": o,
                "weight":      1.5
            },
            tooltip=f"{airport['name']} — {TIME_LABELS[i]} drive"
        ).add_to(m_combined)

# layer 3:airport markers

for airport in AIRPORTS:
    if airport["iata"] in all_isochrones:
        folium.Marker(
            location=[airport["lat"], airport["lon"]],
            tooltip=f"{airport['name']} ({airport['iata']})",
            icon=folium.Icon(color=airport["colour"], icon="plane", prefix="fa")
        ).add_to(m_combined)

# ;ayer control -> this is bassicaly a toggle to turn layers on and off
folium.LayerControl().add_to(m_combined)

# legend for the map

legend_html = """
<div style="position: fixed; bottom: 30px; left: 30px; z-index: 1000;
            background-color: white; padding: 12px 16px;
            border-radius: 8px; border: 1px solid #ccc;
            font-family: Arial; font-size: 13px; line-height: 1.8;">
  <b>Airport Catchment Areas</b><br>
  <span style="color:blue">&#9632;</span> Heathrow (LHR)<br>
  <span style="color:green">&#9632;</span> Gatwick (LGW)<br>
  <span style="color:red">&#9632;</span> Luton (LTN)<br>
  <span style="color:#cccc00">&#9632;</span> ITL3 regions within catchment<br>
  <hr style="margin:4px 0">
  Dark fill = 30 min drive<br>
  Medium fill = 45 min drive<br>
  Light fill = 60 min drive
</div>
"""
m_combined.get_root().html.add_child(folium.Element(legend_html))

print(" Combined map built with 3 layers:")
print(" ITL3 region boundaries")
print(" Isochrone catchment zones")
print(" Airport markers")
print(" Layer toggle added (top right of map)")
m_combined

# addidng bus data
# only kept what I thought i needed from the whole file

coach_df = pd.read_excel('/content/Transport.updated.xlsx')

print(f' Coach stops loaded: {len(coach_df)} stops')
print(f' Columns: {list(coach_df.columns)}')
print(coach_df.head())

# going to have to filter it more

# filter to Southeast England only (around our three airports)
coach_df = coach_df[
    (coach_df['Latitude']  >= 51.0) &
    (coach_df['Latitude']  <= 53.5) &
    (coach_df['Longitude'] >= -2.5) &
    (coach_df['Longitude'] <= 0.5)
].copy()

# keep only BCT stops
coach_df = coach_df[coach_df['StopType'] == 'BCT'].copy()

# reset index
coach_df = coach_df.reset_index(drop=True)

print(f' Coach stops after filtering: {len(coach_df)} stops')
print(coach_df.head())

# converting the stops to geodataframe

coach_gdf = gpd.GeoDataFrame(
    coach_df[['CommonName', 'Longitude', 'Latitude', 'StopType']],
    geometry = gpd.points_from_xy(coach_df['Longitude'], coach_df['Latitude']),
    crs='EPSG:4326'
)

print(f' Coach stops converted to GeoDataFrame: {len(coach_gdf)}')
print(f' CRS: {coach_gdf.crs}')

# adding rail data - zip file

import zipfile

with zipfile.ZipFile('/content/uk-railway-stations-main.zip', 'r') as z:
    with z.open('uk-railway-stations-main/stations.csv') as f:
        rail_df = pd.read_csv(f)

rail_gdf = gpd.GeoDataFrame(
    rail_df,
    geometry=gpd.points_from_xy(rail_df['long'], rail_df['lat']),
    crs='EPSG:4326'
)

print(f' Rail stations loaded: {len(rail_gdf)} stations')
print(f' Columns: {list(rail_df.columns)}')

# adding tube data
# British National Grid - EPSG:27700

tube_df = pd.read_csv('/content/Underground_Stations.csv')

tube_gdf = gpd.GeoDataFrame(
    tube_df,
    geometry=gpd.points_from_xy(tube_df['X'], tube_df['Y']),
    crs='EPSG:27700'
)

# convert to WGS84 to match everything else
tube_gdf = tube_gdf.to_crs(epsg=4326)

print(f' Tube stations loaded: {len(tube_gdf)} stations')
print(f' Networks: {tube_df["NETWORK"].unique()}')
print(f' CRS converted to WGS84')

# spatial join again within the catchment zone

# rail network first

rail_in_catchment = gpd.sjoin(
    rail_gdf,
    isochrones_gdf,
    how='inner',
    predicate='within'
)

rail_summary = (
    rail_in_catchment
    .groupby(['airport_iata', 'time_label'])['stationName']
    .count()
    .reset_index()
    .rename(columns={'stationName': 'rail_count'})
)

print(f' Rail stations within each catchment zone: {len(rail_in_catchment)}')
print(rail_summary.to_string(index=False))

# tube network

tube_in_catchment = gpd.sjoin(
    tube_gdf,
    isochrones_gdf,
    how='inner',
    predicate='within'
)

tube_summary = (
    tube_in_catchment
    .groupby(['airport_iata', 'time_label'])['NAME']
    .count()
    .reset_index()
    .rename(columns={'NAME': 'tube_count'})
)

print(f' Tube stations within each catchment zone: {len(tube_in_catchment)}')
print(tube_summary.to_string(index=False))

# coach data

coach_in_catchment = gpd.sjoin(
    coach_gdf,
    isochrones_gdf,
    how='inner',
    predicate='within'
)

coach_summary = (
    coach_in_catchment
    .groupby(['airport_iata', 'time_label'])['CommonName']
    .count()
    .reset_index()
    .rename(columns={'CommonName': 'coach_count'})
)

print(f' Coach stations within each catchment zone: {len(coach_in_catchment)}')
print(coach_summary.to_string(index=False))

"""For rail ->
LHR has 471 rail stations within 60 mins
LGW has 376, LTN has 246

For tube ->
LHR has 234 tube stations within 60 mins
LGW has 29, LTN has 170

For coach ->
fairly equal across all three airports


"""

# population data

pop_df = pd.read_excel(
    '/content/mye24tablesew.xlsx',
    sheet_name = 'MYE2 - Persons',
    skiprows=7
)

pop_df = pop_df[['Code', 'Name', 'Geography', 'All ages']].copy()
pop_df.columns = ['area_code', 'area_name', 'geography_type', 'population_2024']

# need to filter to Local Authority level only

pop_la = pop_df[pop_df['geography_type'] == 'Metropolitan District'].copy()
pop_la = pd.concat([
    pop_df[pop_df['geography_type'] == 'Non-metropolitan District'],
    pop_df[pop_df['geography_type'] == 'London Borough'],
    pop_df[pop_df['geography_type'] == 'Unitary Authority'],
    pop_df[pop_df['geography_type'] == 'County'],
]).reset_index(drop=True)

print(f' Population data loaded: {len(pop_la)} local authorities')
print(f' Geography types: {pop_la["geography_type"].unique()}')
print(pop_la.head())

# GDHI data - Gross Disposable Household Income

gdhi_df = pd.read_excel(
    '/content/regionalgrossdisposablehouseholdincomeallitlregions2023.xlsx',
    sheet_name = 'Table 1',
    skiprows=1
)

#renaming columns

gdhi_df.columns = ['ITL_level', 'ITL_code', 'Region_name'] + \
                  [str(c) for c in gdhi_df.columns[3:]]

gdhi_itl3 = gdhi_df[gdhi_df['ITL_level'] == 'ITL3'][
    ['ITL_code', 'Region_name', '2023']
].copy()

gdhi_itl3 = gdhi_itl3.rename(columns={'2023': 'GDHI_2023_million_gbp'})
gdhi_itl3 = gdhi_itl3.reset_index(drop=True)

print(f' GDHI data loaded: {len(gdhi_itl3)} ITL3 regions')
print(gdhi_itl3.head())

# joining gdhi to itl3 boundaries

itl3_v2 = itl3.merge(
    gdhi_itl3[['ITL_code', 'GDHI_2023_million_gbp']],
    left_on = 'ITL321CD',
    right_on = 'ITL_code',
    how = 'left'
)

# checking for matches

matched = itl3_v2['GDHI_2023_million_gbp'].notnull().sum()
unmatched = itl3_v2['GDHI_2023_million_gbp'].isnull().sum()

print(f' GDHI joined to ITL3 boundaries')
print(f' Matched: {matched}')
print(f' Unmatched: {unmatched}')
print(itl3_v2[['ITL321CD', 'ITL321NM', 'GDHI_2023_million_gbp']].head())

# a lot of unmatched
# checking to see what the issue is

print("ITL3 boundary codes (first 10):")
print(itl3['ITL321CD'].head(10).tolist())

print("\nGDHI codes (first 10):")
print(gdhi_itl3['ITL_code'].head(10).tolist())

# gdhi files uses a different version of ITL3 codes.
# system might've gotten updated
# trying to match on region name instead

itl3_v2 = itl3.merge(
    gdhi_itl3[['Region_name', 'GDHI_2023_million_gbp']],
    left_on = 'ITL321NM',
    right_on = 'Region_name',
    how = 'left'
)

# checking for matches

matched = itl3_v2['GDHI_2023_million_gbp'].notnull().sum()
unmatched = itl3_v2['GDHI_2023_million_gbp'].isnull().sum()

print(f' GDHI joined on region name')
print(f' Matched: {matched}')
print(f' Unmatched: {unmatched}')


# need to see the unmatched ones in case i need to investigate again

if unmatched > 0:
  print(f' \n Unmatched regions: ')
  print(itl3_v2[itl3_v2['GDHI_2023_million_gbp'].isna()]['ITL321NM'].tolist())

"""update : 157 vs 122 from before.

checked and the issue is in the difference in names between the two files, i.e: north yorkshire cc and north yorshire in the other.

fixing some that i need
"""

# manually fixing names

name_fixes = {
    'North Yorkshire CC':           'North Yorkshire',
    'Barnsley, Doncaster and Rotherham': 'Barnsley, Doncaster and Rotherham',
    'Suffolk CC':                   'Suffolk',
    'Hertfordshire CC':             'Hertfordshire',
    'Camden and City of London':    'Camden & City of London',
    'Westminster':                  'Westminster',
    'Berkshire':                    'Berkshire',
    'Somerset CC':                  'Somerset',
    'Bath and North East Somerset, North Somerset and South Gloucestershire':
        'Bath and North East Somerset, North Somerset and South Gloucestershire',
}

# apply fixes to ITL3 boundary names
itl3_fixed = itl3.copy()
itl3_fixed['ITL321NM_fixed'] = itl3_fixed['ITL321NM'].replace(name_fixes)

# retry the merge with fixed names
itl3_enriched = itl3_fixed.merge(
    gdhi_itl3[['Region_name', 'GDHI_2023_million_gbp']],
    left_on='ITL321NM_fixed',
    right_on='Region_name',
    how='left'
)

matched   = itl3_enriched['GDHI_2023_million_gbp'].notna().sum()
unmatched = itl3_enriched['GDHI_2023_million_gbp'].isna().sum()

print(f' Matched: {matched} regions')
print(f' Unmatched: {unmatched} regions')

"""20 unmatched regions - checking to see if any are near our airpots

"""

unmatched_regions = itl3_v2[
    itl3_v2['GDHI_2023_million_gbp'].isna()
]['ITL321NM'].tolist()

#checking overlap

catchment_regions = joined['ITL321NM'].unique().tolist()

problem_regions = [r for r in unmatched_regions if r in catchment_regions]

if len(problem_regions) == 0:
  print(' None of the unmatched regions are within our catchment zones')
  print(' Good to go. GDHI data is ok for our ares')
else:
  print(f' The unmatched regions are within the catchemnt zones: ')
  print(problem_regions)

"""these four are important so i need to see how to fix them"""

# finding the exat anmes in the gdhi file

search_terms = ['Hertfordshire', 'Camden', 'Westminster', 'Berkshire']

for term in search_terms:
  matches = gdhi_itl3[gdhi_itl3['Region_name'].str.contains(term, case=False)]
  print(f' {term}: ')
  print(matches[['ITL_code', 'Region_name']].to_string(index=False))
  print()

"""so the zones are split into sub-regions. great"""

split_regions = {
    'Hertfordshire CC': ['North and East Hertfordshire', 'South West Hertfordshire'],
    'Camden and City of London': ['Camden', 'Westminster and City of London'],
    'Westminster': ['Westminster and City of London'],
    'Berkshire': ['Berkshire East', 'Berkshire West'],
}

fix_rows = []
for boundary_name, gdhi_names in split_regions.items():
    total_gdhi = gdhi_itl3[
        gdhi_itl3['Region_name'].isin(gdhi_names)
    ]['GDHI_2023_million_gbp'].sum()
    fix_rows.append({
        'Region_name': boundary_name,
        'GDHI_2023_million_gbp': total_gdhi
    })

gdhi_fixes = pd.DataFrame(fix_rows)
print(' GDHI fixes calculated: ')
print(gdhi_fixes.to_string(index=False))

for _, fix_row in gdhi_fixes.iterrows():
    mask = itl3_v2['ITL321NM'] == fix_row['Region_name']
    itl3_v2.loc[mask, 'GDHI_2023_million_gbp'] = fix_row['GDHI_2023_million_gbp']

# checking again for to see the match count
matched   = itl3_v2['GDHI_2023_million_gbp'].notna().sum()
unmatched = itl3_v2['GDHI_2023_million_gbp'].isna().sum()

print(f' \n Final matched: {matched} regions')
print(f' Remaining unmatched: {unmatched} regions')

"""checking again for the 4 zones, the other 18 are in wales or scotland which we dont need

"""

unmatched_names = itl3_v2[
    itl3_v2['GDHI_2023_million_gbp'].isna()
]['ITL321NM'].tolist()

catchment_regions = joined['ITL321NM'].unique().tolist()
problem_regions = [r for r in unmatched_names if r in catchment_regions]

if len(problem_regions) == 0:
    print(' All catchment regions have GDHI data')
    print(f'  Remaining 18 unmatched are outside catchment zones')
    print(f'\n  Unmatched regions (for reference): ')
    for r in unmatched_names:
        print(f'    - {r}')
else:
    print(f' Still missing GDHI for these catchment regions: ')
    print(problem_regions)

# joining the population data
# checking to see what geography types are in the file

print(f' All geography types in the pop data: ')
print(pop_df['geography_type'].value_counts().to_string())

"""this is at local authority level. need to find another link for the ITL3

"""

# found the data

lookup_df = pd.read_csv(
    '/content/LAD_(December_2024)_to_LAU1_to_ITL3_to_ITL2_to_ITL1_(January_2025)_Lookup_in_the_UK.csv',
)

print(f' Lookup table loaded: {len(lookup_df)} rows')
print(f' Columns: {list(lookup_df.columns)}')

# joining population to lookup table using Local Authority code
pop_itl3 = lookup_df.merge(
    pop_df[['area_code', 'population_2024']],
    left_on='LAD24CD',
    right_on='area_code',
    how='left'
)

# aggregate population up to ITL3 level
pop_itl3_agg = (
    pop_itl3
    .groupby(['ITL325CD', 'ITL325NM'])['population_2024']
    .sum()
    .reset_index()
    .rename(columns={'ITL325NM': 'Region_name'})
)

print(f'\n Population aggregated to ITL3: {len(pop_itl3_agg)} regions')
print(pop_itl3_agg.head())

"""same issue here as before. need to check the unmathced regions"""

# Clean up itl3_v2 columns completely
# Drop all population columns and start fresh
cols_to_drop = [col for col in itl3_v2.columns if 'population' in col]
print(f'Dropping columns: {cols_to_drop}')
itl3_v2 = itl3_v2.drop(columns=cols_to_drop)

# Re-merge population cleanly
itl3_v2 = itl3_v2.merge(
    pop_itl3_agg[['ITL325CD', 'population_2024']],
    left_on='ITL321CD',
    right_on='ITL325CD',
    how='left'
)

print(f'✓ Columns now: {list(itl3_v2.columns)}')
print(f'  Matched: {itl3_v2["population_2024"].notna().sum()} regions')

unmatched_names = itl3_v2[
    itl3_v2['population_2024'].isna()
]['ITL321NM'].tolist()

catchment_regions = joined['ITL321NM'].unique().tolist()
problem_regions = [r for r in unmatched_names if r in catchment_regions]

if len(problem_regions) == 0:
    print(' All catchment regions have population data — safe to proceed')
else:
    print(f' Missing population data for these catchment regions:')
    for r in problem_regions:
        print(f'  - {r}')

pop_fixes = {
    'Hertfordshire CC': ['North Hertfordshire', 'East Hertfordshire',
                         'Welwyn Hatfield', 'Stevenage', 'St Albans',
                         'Watford', 'Three Rivers', 'Hertsmere',
                         'Broxbourne', 'Dacorum'],
    'Camden and City of London': ['Camden', 'City of London'],
    'Westminster': ['Westminster'],
    'Berkshire': ['Reading', 'Slough', 'Windsor and Maidenhead',
                  'Bracknell Forest', 'Wokingham', 'West Berkshire'],
}

for boundary_name, la_names in pop_fixes.items():
    total_pop = pop_df[
        pop_df['area_name'].isin(la_names)
    ]['population_2024'].sum()

    mask = itl3_v2['ITL321NM'] == boundary_name
    itl3_v2.loc[mask, 'population_2024'] = total_pop
    print(f' {boundary_name}: {total_pop:,.0f} people')

# final check
matched   = itl3_v2['population_2024'].notna().sum()
unmatched = itl3_v2['population_2024'].isna().sum()
print(f'\n Final matched: {matched} regions')
print(f' Remaining unmatched: {unmatched} regions')

unmatched_names = itl3_v2[
    itl3_v2['population_2024'].isna()
]['ITL321NM'].tolist()

catchment_regions = joined['ITL321NM'].unique().tolist()
problem_regions = [r for r in unmatched_names if r in catchment_regions]

if len(problem_regions) == 0:
    print(' All catchment regions have population data')
    print(f'\n  Summary of itl3_v2:')
    print(f' Total regions: {len(itl3_v2)}')
    print(f' Regions with population: {itl3_v2["population_2024"].notna().sum()}')
    print(f' Regions with GDHI: {itl3_v2["GDHI_2023_million_gbp"].notna().sum()}')
    print(f'\n  Columns: {list(itl3_v2.columns)}')
else:
    print(f' Still missing population for these catchment regions:')
    for r in problem_regions:
        print(f'  - {r}')

"""summary: itl3_v2 has - itl3 boundaries(geometry), region names and codes, GDHI wealth data(2023) and pop data (2024)

the final map will have:
Isochrones - 3 airports, 3 time bands
pop and GDHI
rail stations
tube sations
coach stops


"""

print(coach_in_catchment.columns.tolist())

# Reduce coach stops to a manageable number
# Keep 1 in every 10 stops
coach_reduced = coach_in_catchment.groupby(
    ['airport_iata', 'time_label']
).apply(lambda x: x.sample(frac=0.1, random_state=42)).reset_index(drop=True)

print(f' Coach stops reduced from {len(coach_in_catchment)} to {len(coach_reduced)}')
print(coach_reduced.groupby(['airport_iata', 'time_label'])['CommonName'].count())

# another map

from folium.plugins import MarkerCluster

m_final = folium.Map(
    location=[51.5, -0.3],
    zoom_start=7,
    tiles='CartoDB positron'
)

# LAYER 1: Population
# Only show ITL3 regions within catchment zones
catchment_codes = joined['ITL321CD'].unique()
itl3_catchment_only = itl3_v2[itl3_v2['ITL321CD'].isin(catchment_codes)]

folium.Choropleth(
    geo_data=itl3_catchment_only.__geo_interface__,
    data=itl3_catchment_only,
    columns=['ITL321NM', 'population_2024'],
    key_on='feature.properties.ITL321NM',
    fill_color='YlOrRd',
    fill_opacity=0.5,
    line_opacity=0.2,
    legend_name='Population (2024)',
    name='Population by ITL3 region',
    nan_fill_color='lightgrey'
).add_to(m_final)

# LAYER 2: Isochrones
colours = {'LHR': 'blue', 'LGW': 'red', 'LTN': 'green'}

for iata, geojson in all_isochrones.items():
    colour = colours[iata]
    for i, feature in enumerate(geojson['features']):
        folium.GeoJson(
            feature,
            name=f"{iata} — {TIME_LABELS[i]}",
            style_function=lambda x, c=colour: {
                'fillColor':   c,
                'color':       c,
                'fillOpacity': 0,
                'weight':      2.5
            },
            tooltip=f"{iata} — {TIME_LABELS[i]} drive"
        ).add_to(m_final)

# LAYER 3: Rail stations (dark blue)
rail_cluster = MarkerCluster(name='Rail Stations').add_to(m_final)
for _, row in rail_in_catchment.iterrows():
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=5,
        color='darkblue',
        fill=True,
        fill_color='darkblue',
        fill_opacity=0.8,
        tooltip=f" {row['stationName']}"
    ).add_to(rail_cluster)

# LAYER 4: Tube stations (dark red)
tube_cluster = MarkerCluster(name=' Tube Stations').add_to(m_final)
for _, row in tube_in_catchment.iterrows():
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=5,
        color='darkred',
        fill=True,
        fill_color='darkred',
        fill_opacity=0.8,
        tooltip=f" {row['NAME']}"
    ).add_to(tube_cluster)

# LAYER 5: Coach stops (dark green, reduced)
coach_cluster = MarkerCluster(name=' Coach Stops').add_to(m_final)
for _, row in coach_reduced.iterrows():
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=3,
        color='darkgreen',
        fill=True,
        fill_color='darkgreen',
        fill_opacity=0.6,
        tooltip=f" {row['CommonName']}"
    ).add_to(coach_cluster)

# LAYER 6: Airport markers
for airport in AIRPORTS:
    if airport['iata'] in all_isochrones:
        folium.Marker(
            location=[airport['lat'], airport['lon']],
            tooltip=f"✈ {airport['name']} ({airport['iata']})",
            icon=folium.Icon(
                color=airport['colour'],
                icon='plane',
                prefix='fa'
            )
        ).add_to(m_final)

# LAYER CONTROL
folium.LayerControl(collapsed=False).add_to(m_final)

# LEGEND
legend_html = """
<div style="position: fixed; bottom: 30px; left: 30px; z-index: 1000;
            background-color: white; padding: 12px 16px;
            border-radius: 8px; border: 1px solid #ccc;
            font-family: Arial; font-size: 12px; line-height: 1.9;">
  <b>Airport Catchment Analysis</b><br>
  ✈ <span style="color:blue">Heathrow (LHR)</span><br>
  ✈ <span style="color:red">Gatwick (LGW)</span><br>
  ✈ <span style="color:green">Luton (LTN)</span><br>
  <hr style="margin:4px 0">
   Dark blue = Rail stations<br>
   Dark red = Tube stations<br>
   Dark green = Coach stops<br>
  <hr style="margin:4px 0">
  Yellow→Red shading = Population<br>
  Coloured outlines = 30/45/60 min drive<br>
  <hr style="margin:4px 0">
  <i>Use layer toggle (top right)<br>to show/hide layers</i>
</div>
"""
m_final.get_root().html.add_child(folium.Element(legend_html))
m_final

# Deduplicate all transport layers
rail_dedup  = rail_in_catchment.drop_duplicates(subset=['stationName']).copy()
tube_dedup  = tube_in_catchment.drop_duplicates(subset=['NAME']).copy()
coach_dedup = coach_reduced.drop_duplicates(subset=['CommonName']).copy()

print(f'Rail:  {len(rail_in_catchment):,} → {len(rail_dedup):,}')
print(f'Tube:  {len(tube_in_catchment):,} → {len(tube_dedup):,}')
print(f'Coach: {len(coach_reduced):,} → {len(coach_dedup):,}')

# FINAL MAP — with deduplicated transport layers
from folium.plugins import MarkerCluster

m_final = folium.Map(
    location=[51.5, -0.3],
    zoom_start=7,
    tiles='CartoDB positron'
)

# LAYER 1: Population
# Only show ITL3 regions within catchment zones
catchment_codes = joined['ITL321CD'].unique()
itl3_catchment_only = itl3_v2[itl3_v2['ITL321CD'].isin(catchment_codes)]

folium.Choropleth(
    geo_data=itl3_catchment_only.__geo_interface__,
    data=itl3_catchment_only,
    columns=['ITL321NM', 'population_2024'],
    key_on='feature.properties.ITL321NM',
    fill_color='YlOrRd',
    fill_opacity=0.5,
    line_opacity=0.2,
    legend_name='Population (2024)',
    name='Population by ITL3 region',
    nan_fill_color='lightgrey'
).add_to(m_final)

# LAYER 2: Isochrones
colours = {'LHR': 'blue', 'LGW': 'red', 'LTN': 'green'}

for iata, geojson in all_isochrones.items():
    colour = colours[iata]
    for i, feature in enumerate(geojson['features']):
        folium.GeoJson(
            feature,
            name=f"{iata} — {TIME_LABELS[i]}",
            style_function=lambda x, c=colour: {
                'fillColor':   c,
                'color':       c,
                'fillOpacity': 0,
                'weight':      2.5
            },
            tooltip=f"{iata} — {TIME_LABELS[i]} drive"
        ).add_to(m_final)

# LAYER 3: Rail stations (blue cluster)
fg_rail = folium.FeatureGroup(name=' Rail Stations', show=False)
cluster_rail = MarkerCluster(
    icon_create_function="""
    function(cluster) {
        return L.divIcon({
            html: '<div style="background-color:#00008B; color:white; border-radius:50%; width:30px; height:30px; display:flex; align-items:center; justify-content:center; font-weight:bold; font-size:11px;">' + cluster.getChildCount() + '</div>',
            className: '',
            iconSize: [30, 30]
        });
    }"""
).add_to(fg_rail)

for _, row in rail_dedup.iterrows():
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=5,
        color='darkblue',
        fill=True,
        fill_color='darkblue',
        fill_opacity=0.8,
        tooltip=f" {row['stationName']}"
    ).add_to(cluster_rail)
fg_rail.add_to(m_final)

# LAYER 4: Tube stations (red cluster)
fg_tube = folium.FeatureGroup(name='Tube Stations', show=False)
cluster_tube = MarkerCluster(
    icon_create_function="""
    function(cluster) {
        return L.divIcon({
            html: '<div style="background-color:#8B0000; color:white; border-radius:50%; width:30px; height:30px; display:flex; align-items:center; justify-content:center; font-weight:bold; font-size:11px;">' + cluster.getChildCount() + '</div>',
            className: '',
            iconSize: [30, 30]
        });
    }"""
).add_to(fg_tube)

for _, row in tube_dedup.iterrows():
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=5,
        color='darkred',
        fill=True,
        fill_color='darkred',
        fill_opacity=0.8,
        tooltip=f" {row['NAME']}"
    ).add_to(cluster_tube)
fg_tube.add_to(m_final)

# LAYER 5: Coach stops (green cluster)
fg_coach = folium.FeatureGroup(name=' Coach Stops', show=False)
cluster_coach = MarkerCluster(
    icon_create_function="""
    function(cluster) {
        return L.divIcon({
            html: '<div style="background-color:#006400; color:white; border-radius:50%; width:30px; height:30px; display:flex; align-items:center; justify-content:center; font-weight:bold; font-size:11px;">' + cluster.getChildCount() + '</div>',
            className: '',
            iconSize: [30, 30]
        });
    }"""
).add_to(fg_coach)

for _, row in coach_dedup.iterrows():
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=3,
        color='darkgreen',
        fill=True,
        fill_color='darkgreen',
        fill_opacity=0.6,
        tooltip=f" {row['CommonName']}"
    ).add_to(cluster_coach)
fg_coach.add_to(m_final)

# LAYER 6: Airport markers
for airport in AIRPORTS:
    if airport['iata'] in all_isochrones:
        folium.Marker(
            location=[airport['lat'], airport['lon']],
            tooltip=f"✈ {airport['name']} ({airport['iata']})",
            icon=folium.Icon(
                color=airport['colour'],
                icon='plane',
                prefix='fa'
            )
        ).add_to(m_final)

# LAYER CONTROL
folium.LayerControl(collapsed=False).add_to(m_final)

# LEGEND
legend_html = """
<div style="position: fixed; bottom: 30px; left: 30px; z-index: 1000;
            background-color: white; padding: 12px 16px;
            border-radius: 8px; border: 1px solid #ccc;
            font-family: Arial; font-size: 12px; line-height: 1.9;">
  <b>Airport Catchment Analysis</b><br>
  ✈ <span style="color:blue">Heathrow (LHR)</span><br>
  ✈ <span style="color:red">Gatwick (LGW)</span><br>
  ✈ <span style="color:green">Luton (LTN)</span><br>
  <hr style="margin:4px 0">
   Dark blue = Rail stations<br>
   Dark red = Tube stations<br>
   Dark green = Coach stops<br>
  <hr style="margin:4px 0">
  Yellow→Red shading = Population<br>
  Coloured outlines = 30/45/60 min drive<br>
  <hr style="margin:4px 0">
  <i>Use layer toggle (top right)<br>to show/hide layers</i>
</div>
"""
m_final.get_root().html.add_child(folium.Element(legend_html))
m_final

ORS_API_KEY = 'eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjE2YzYyMzI0OWZlYzRiNzJiYjI2MDAzZmRlZmY4ZjRiIiwiaCI6Im11cm11cjY0In0='

# Test with a single point
url = 'https://api.openrouteservice.org/v2/directions/driving-car/geojson'

body = {
    'coordinates': [
        [0.1218, 52.2053],   # Cambridge town centre
        [-0.4614, 51.4775]   # Heathrow
    ]
}

response = requests.post(url, json=body, headers={
    'Authorization': ORS_API_KEY,
    'Content-Type': 'application/json'
})

print(f'Status: {response.status_code}')
if response.status_code == 200:
    data = response.json()
    mins = round(data['features'][0]['properties']['summary']['duration'] / 60)
    km   = round(data['features'][0]['properties']['summary']['distance'] / 1000, 1)
    print(f' API working — Cambridge to Heathrow: {mins} min · {km} km')
else:
    print(response.text[:300])

"""tested one random point within the api to see if i can actually do it. it finally worked."""

from shapely.geometry import Point
ORS_API_KEY = 'eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjE2YzYyMzI0OWZlYzRiNzJiYjI2MDAzZmRlZmY4ZjRiIiwiaCI6Im11cm11cjY0In0='

# Airport road-accessible coordinates (slightly adjusted from terminal)
AIRPORT_COORDS = {
    'LHR': {'name': 'London Heathrow', 'lat': 51.4706, 'lon': -0.4541, 'colour': 'blue'},
    'LGW': {'name': 'London Gatwick',  'lat': 51.1537, 'lon': -0.1821, 'colour': 'red'},
    'LTN': {'name': 'London Luton',    'lat': 51.8796, 'lon': -0.3713, 'colour': 'green'},
}

# ── Set your start point here ────────────────────────────────
# Change these coordinates to any point within the catchment
START_LAT = 51.7520   # Oxford
START_LON = -1.2577

print(f'Start point: {START_LAT}, {START_LON}')
print(f'Airports: {list(AIRPORT_COORDS.keys())}')
print(' Configuration ready')

# ── Find nearest transport stops to start point

start_point = Point(START_LON, START_LAT)
start_gdf   = gpd.GeoDataFrame(geometry=[start_point], crs='EPSG:4326')

def find_nearest_stop(stops_gdf, start_point, name_col):
    """Find the single nearest stop to a given point."""
    distances = stops_gdf.geometry.distance(start_point)
    nearest_idx = distances.idxmin()
    nearest_row = stops_gdf.loc[nearest_idx]
    dist_km = distances[nearest_idx] * 111  # rough degrees to km
    return nearest_row, round(dist_km, 2)

# Find nearest of each type
nearest_rail,  dist_rail  = find_nearest_stop(rail_dedup,  start_point, 'stationName')
nearest_tube,  dist_tube  = find_nearest_stop(tube_dedup,  start_point, 'NAME')
nearest_coach, dist_coach = find_nearest_stop(coach_dedup, start_point, 'CommonName')

print(f' Nearest rail station : {nearest_rail["stationName"]} ({dist_rail} km)')
print(f' Nearest tube station : {nearest_tube["NAME"]} ({dist_tube} km)')
print(f' Nearest coach stop   : {nearest_coach["CommonName"]} ({dist_coach} km)')

import requests
import time

# Fix CRS warning by projecting to BNG first

def find_nearest_stop_projected(stops_gdf, start_lat, start_lon, name_col):
    """Find nearest stop using projected CRS for accurate distances."""
    start_point_bng = gpd.GeoDataFrame(
        geometry=[Point(start_lon, start_lat)], crs='EPSG:4326'
    ).to_crs('EPSG:27700').geometry.iloc[0]

    stops_projected = stops_gdf.to_crs('EPSG:27700')
    distances = stops_projected.geometry.distance(start_point_bng)
    nearest_idx = distances.idxmin()
    nearest_row = stops_gdf.loc[nearest_idx]
    dist_km = round(distances[nearest_idx] / 1000, 2)
    return nearest_row, dist_km

# Recalculate with correct projection
nearest_rail,  dist_rail  = find_nearest_stop_projected(rail_dedup,  START_LAT, START_LON, 'stationName')
nearest_tube,  dist_tube  = find_nearest_stop_projected(tube_dedup,  START_LAT, START_LON, 'NAME')
nearest_coach, dist_coach = find_nearest_stop_projected(coach_dedup, START_LAT, START_LON, 'CommonName')

print(f'✓ Nearest rail station : {nearest_rail["stationName"]} ({dist_rail} km)')
print(f'✓ Nearest tube station : {nearest_tube["NAME"]} ({dist_tube} km)')
print(f'✓ Nearest coach stop   : {nearest_coach["CommonName"]} ({dist_coach} km)')

# Fetch driving routes via ORS
def get_driving_route(from_lon, from_lat, to_lon, to_lat, api_key):
    """Get driving route between two points via ORS."""
    url = 'https://api.openrouteservice.org/v2/directions/driving-car/geojson'
    body = {'coordinates': [[from_lon, from_lat], [to_lon, to_lat]]}
    response = requests.post(url, json=body, headers={
        'Authorization': api_key,
        'Content-Type': 'application/json'
    })
    if response.status_code == 200:
        data = response.json()
        summary = data['features'][0]['properties']['summary']
        coords  = data['features'][0]['geometry']['coordinates']
        return {
            'duration_min': round(summary['duration'] / 60),
            'distance_km':  round(summary['distance'] / 1000, 1),
            'coords':       [[c[1], c[0]] for c in coords]  # flip to lat/lon for folium
        }
    else:
        print(f'  ✗ Route error: {response.status_code}')
        return None

# Fetch driving routes to all airports

print('\nFetching driving routes...')
drive_routes = {}
for iata, ap in AIRPORT_COORDS.items():
    print(f'  {iata}...', end=' ')
    route = get_driving_route(START_LON, START_LAT, ap['lon'], ap['lat'], ORS_API_KEY)
    if route:
        drive_routes[iata] = route
        print(f'{route["duration_min"]} min · {route["distance_km"]} km')
    time.sleep(0.5)

# Fetch driving routes from start to nearest stops

print('\nFetching routes to nearest stops...')
stop_routes = {}

for stop_name, stop_row, stop_type in [
    (nearest_rail['stationName'], nearest_rail, 'rail'),
    (nearest_tube['NAME'],        nearest_tube,  'tube'),
    (nearest_coach['CommonName'], nearest_coach, 'coach'),
]:
    print(f'  To {stop_name}...', end=' ')
    route = get_driving_route(
        START_LON, START_LAT,
        stop_row.geometry.x, stop_row.geometry.y,
        ORS_API_KEY
    )
    if route:
        stop_routes[stop_type] = {
            'name':   stop_name,
            'route':  route,
            'coords': [stop_row.geometry.y, stop_row.geometry.x]
        }
        print(f'{route["duration_min"]} min · {route["distance_km"]} km')
    time.sleep(0.5)

print('\n All routes fetched')

"""gatwick seems to be in a restriced area hence the 404 error. trying to work around it"""

# Fix Gatwick coordinates, use the road outside the terminal

AIRPORT_COORDS['LGW']['lat'] = 51.1564
AIRPORT_COORDS['LGW']['lon'] = -0.1622

# Retry LGW only

print('Retrying LGW...')
route = get_driving_route(START_LON, START_LAT,
                          AIRPORT_COORDS['LGW']['lon'],
                          AIRPORT_COORDS['LGW']['lat'],
                          ORS_API_KEY)
if route:
    drive_routes['LGW'] = route
    print(f' LGW: {route["duration_min"]} min · {route["distance_km"]} km')

os.makedirs('/content/drive/MyDrive/catchment_data', exist_ok=True)

# Save isochrones to Drive
for iata, geojson in all_isochrones.items():
    path = f'/content/drive/MyDrive/catchment_data/{iata}_isochrones.geojson'
    with open(path, 'w') as f:
        json.dump(geojson, f)
    print(f' Saved {iata}')

all_isochrones = {}
for iata in ['LHR', 'LGW', 'LTN']:
    path = f'/content/drive/MyDrive/catchment_data/{iata}_isochrones.geojson'
    with open(path, 'r') as f:
        all_isochrones[iata] = json.load(f)
    print(f' Loaded {iata}')

from shapely.ops import unary_union
# Build union of all 60 min isochrones

all_polys = []
for iata in ['LHR', 'LGW', 'LTN']:
    features = all_isochrones[iata]['features']
    # Get the 60 min zone (last feature — largest zone)
    geom = shape(features[-1]['geometry'])
    all_polys.append(geom)

combined = unary_union(all_polys)
combined_gdf = gpd.GeoDataFrame(geometry=[combined], crs='EPSG:4326')

# Filter ITL3 by centroid inside catchment
itl3_projected     = itl3_v2.to_crs('EPSG:27700').copy()
combined_projected = combined_gdf.to_crs('EPSG:27700').geometry.iloc[0]
itl3_projected['inside'] = itl3_projected.geometry.centroid.within(combined_projected)
itl3_catchment_filtered  = itl3_v2[itl3_projected['inside'].values].copy()

print(f' itl3_catchment_filtered: {len(itl3_catchment_filtered)} regions')

import json

# Export all data for HTML

# Isochrones
iso_geojson = {}
for iata, geojson in all_isochrones.items():
    iso_geojson[iata] = geojson

# Transport stops
rail_json  = json.loads(rail_dedup[['stationName', 'geometry']].to_json())
tube_json  = json.loads(tube_dedup[['NAME', 'LINES', 'geometry']].to_json())
coach_json = json.loads(coach_dedup[['CommonName', 'geometry']].head(2000).to_json())

# ITL3 catchment
itl3_json = json.loads(
    itl3_catchment_filtered[['ITL321NM', 'population_2024', 'GDHI_2023_million_gbp', 'geometry']].to_json()
)

print(f' Rail stops:   {len(rail_dedup)}')
print(f' Tube stops:   {len(tube_dedup)}')
print(f' Coach stops:  {min(2000, len(coach_dedup))}')
print(f' ITL3 regions: {len(itl3_catchment_filtered)}')
print(' All data ready for HTML export')

"""all ready to see if it is gonna be an interactive map or not"""

html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>London Airport Catchment — Interactive Journey Planner</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js"></script>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family: Arial, sans-serif; height:100vh; display:flex; flex-direction:column; }}
  #header {{ background:#1a1a2e; color:white; padding:10px 20px; display:flex; align-items:center; justify-content:space-between; flex-shrink:0; }}
  #header h1 {{ font-size:14px; font-weight:bold; letter-spacing:0.05em; }}
  #api-bar {{ background:#0d1525; padding:6px 20px; display:flex; align-items:center; gap:10px; flex-shrink:0; border-bottom:1px solid #2a3a50; }}
  #api-bar label {{ font-size:11px; color:#888; white-space:nowrap; }}
  #api-bar input {{ flex:1; background:#1e2d45; border:1px solid #2a3a50; color:white; padding:4px 8px; font-size:11px; border-radius:3px; }}
  #main {{ display:flex; flex:1; overflow:hidden; }}
  #map {{ flex:1; }}
  #sidebar {{ width:340px; background:#111827; color:#e2e8f0; display:flex; flex-direction:column; overflow:hidden; border-left:1px solid #1e2d45; flex-shrink:0; }}
  #sidebar-title {{ padding:12px 16px; border-bottom:1px solid #1e2d45; font-size:12px; font-weight:bold; text-transform:uppercase; letter-spacing:0.08em; color:#94a3b8; }}
  #instruction {{ padding:10px 16px; border-bottom:1px solid #1e2d45; font-size:11px; color:#64748b; line-height:1.5; }}
  #results {{ flex:1; overflow-y:auto; padding:10px; }}
  .airport-block {{ margin-bottom:10px; border:1px solid #1e2d45; border-radius:6px; overflow:hidden; }}
  .airport-header {{ padding:8px 12px; display:flex; align-items:center; gap:8px; border-bottom:1px solid #1e2d45; font-size:12px; font-weight:bold; }}
  .dot {{ width:8px; height:8px; border-radius:50%; flex-shrink:0; }}
  .route-row {{ padding:7px 12px; display:flex; align-items:center; justify-content:space-between; border-bottom:1px solid #1e2d45; font-size:11px; cursor:pointer; transition:background 0.1s; }}
  .route-row:last-child {{ border-bottom:none; }}
  .route-row:hover {{ background:rgba(255,255,255,0.04); }}
  .route-left {{ display:flex; align-items:center; gap:8px; }}
  .route-icon {{ width:20px; height:20px; border-radius:3px; display:flex; align-items:center; justify-content:center; font-size:11px; flex-shrink:0; }}
  .route-label {{ font-size:11px; line-height:1.3; }}
  .route-sub {{ font-size:9px; color:#64748b; }}
  .route-val {{ color:#94a3b8; font-size:11px; white-space:nowrap; }}
  .route-val.done {{ color:#e2e8f0; }}
  .spinner {{ width:11px; height:11px; border:2px solid #1e2d45; border-top-color:#64748b; border-radius:50%; animation:spin 0.7s linear infinite; flex-shrink:0; }}
  @keyframes spin {{ to {{ transform:rotate(360deg); }} }}
  #empty {{ padding:30px 16px; text-align:center; font-size:11px; color:#64748b; line-height:1.7; }}
  #coords {{ padding:5px 16px; border-top:1px solid #1e2d45; font-size:10px; color:#475569; }}
  #legend {{ padding:8px 16px; border-top:1px solid #1e2d45; display:flex; flex-wrap:wrap; gap:8px; }}
  .leg {{ display:flex; align-items:center; gap:4px; font-size:10px; color:#64748b; }}
  .leg-line {{ width:16px; height:3px; border-radius:1px; }}
  #loading-bar {{ padding:6px 16px; font-size:10px; color:#f59e0b; display:none; border-top:1px solid #1e2d45; }}
  .leaflet-popup-content-wrapper {{ background:#1e2d45; color:#e2e8f0; font-family:Arial; font-size:11px; border-radius:5px; }}
  .leaflet-popup-tip {{ background:#1e2d45; }}
</style>
</head>
<body>

<div id="header">
  <h1>✈ London Airport Catchment — Interactive Journey Planner</h1>
  <span style="font-size:11px;color:#64748b;">University of Westminster · SAC Project</span>
</div>

<div id="api-bar">
  <label>ORS API KEY:</label>
  <input type="password" id="apiKey" placeholder="Paste your OpenRouteService API key…"/>
</div>

<div id="main">
  <div id="map"></div>
  <div id="sidebar">
    <div id="sidebar-title">Journey Routes</div>
    <div id="instruction">
      Click anywhere on the map to calculate routes to all three airports.<br><br>
      Transport routes show the <b>full journey</b>: start → nearest stop → airport.
      Click any row to highlight that route.
    </div>
    <div id="results">
      <div id="empty">Click anywhere on the map<br>to calculate journey times.</div>
    </div>
    <div id="loading-bar">⏳ Loading routes... please wait (~20s)</div>
    <div id="legend">
      <div class="leg"><div class="leg-line" style="background:#ff8800"></div>Drive</div>
      <div class="leg"><div class="leg-line" style="background:#00ccff"></div>Rail</div>
      <div class="leg"><div class="leg-line" style="background:#ff00ff"></div>Tube</div>
      <div class="leg"><div class="leg-line" style="background:#00ff88"></div>Coach</div>
      <div class="leg"><div class="leg-line" style="background:#ff00ff;opacity:0.4;border-top:2px dashed #ff00ff"></div>→ stop</div>
      <div class="leg"><div class="leg-line" style="background:#ff00ff;opacity:1"></div>stop → ✈</div>
    </div>
    <div id="coords">Coordinates: —</div>
  </div>
</div>

<script>
const ISO_DATA   = {json.dumps(iso_geojson)};
const RAIL_DATA  = {json.dumps(rail_json)};
const TUBE_DATA  = {json.dumps(tube_json)};
const COACH_DATA = {json.dumps(coach_json)};
const ITL3_DATA  = {json.dumps(itl3_json)};

const AIRPORTS = {{
  LHR: {{ name:'London Heathrow', lat:51.4706, lon:-0.4541, colour:'#3b82f6' }},
  LGW: {{ name:'London Gatwick',  lat:51.1564, lon:-0.1622, colour:'#ef4444' }},
  LTN: {{ name:'London Luton',    lat:51.8796, lon:-0.3713, colour:'#22c55e' }},
}};

// Distinct bright colours that contrast with the catchment zone outlines
const ROUTE_COLOURS = {{
  drive: '#ff8800',   // bright orange
  rail:  '#00ccff',   // bright cyan
  tube:  '#ff00ff',   // bright magenta
  coach: '#00ff88',   // bright lime
}};

const isoColours = {{ LHR:'#3b82f6', LGW:'#ef4444', LTN:'#22c55e' }};
const TIMES = [30, 45, 60];

// ── Map ───────────────────────────────────────────────────────
const map = L.map('map').setView([51.5, -0.3], 8);
L.tileLayer('https://{{s}}.basemaps.cartocdn.com/dark_all/{{z}}/{{x}}/{{y}}{{r}}.png', {{
  attribution:'© OpenStreetMap © CARTO', maxZoom:18
}}).addTo(map);

// ── ITL3 choropleth ───────────────────────────────────────────
const pops = ITL3_DATA.features.map(f => f.properties.population_2024 || 0);
const minPop = Math.min(...pops), maxPop = Math.max(...pops);
function popColour(pop) {{
  if (!pop) return '#374151';
  const t = (pop - minPop) / (maxPop - minPop);
  const r = Math.round(255 * Math.min(1, t * 2));
  const g = Math.round(255 * Math.max(0, 1 - t * 2));
  return `rgb(${{r}},${{g}},50)`;
}}
L.geoJSON(ITL3_DATA, {{
  style: f => ({{ fillColor: popColour(f.properties.population_2024), color:'#374151', weight:0.5, fillOpacity:0.5 }}),
  onEachFeature: (f, layer) => {{
    const p = f.properties;
    layer.bindTooltip(`<b>${{p.ITL321NM}}</b><br>Population: ${{(p.population_2024||0).toLocaleString()}}<br>GDHI: £${{(p.GDHI_2023_million_gbp||0).toLocaleString()}}M`, {{sticky:true}});
  }}
}}).addTo(map);

// ── Isochrones ────────────────────────────────────────────────
Object.entries(ISO_DATA).forEach(([iata, geojson]) => {{
  geojson.features.forEach((feature, i) => {{
    L.geoJSON(feature, {{ style: {{ color:isoColours[iata], weight:[2.5,1.8,1.2][i], fillOpacity:0, opacity:0.9 }} }})
      .bindTooltip(`${{iata}} — ${{TIMES[i]}} min drive`).addTo(map);
  }});
}});

// ── Airport markers ───────────────────────────────────────────
Object.entries(AIRPORTS).forEach(([code, ap]) => {{
  L.marker([ap.lat, ap.lon], {{
    icon: L.divIcon({{
      html:`<div style="background:${{ap.colour}};color:white;border-radius:50%;width:32px;height:32px;display:flex;align-items:center;justify-content:center;font-size:9px;font-weight:bold;border:2px solid rgba(255,255,255,0.4);box-shadow:0 0 10px ${{ap.colour}}88;">✈${{code}}</div>`,
      className:'', iconSize:[32,32], iconAnchor:[16,16]
    }})
  }}).addTo(map).bindPopup(`<b>✈ ${{ap.name}}</b><br>${{code}}`);
}});

// ── Transport layers ──────────────────────────────────────────
function makeLayer(data, colour, nameField, emoji) {{
  const layer = L.layerGroup();
  data.features.forEach(f => {{
    const [lon, lat] = f.geometry.coordinates;
    L.circleMarker([lat, lon], {{ radius:4, color:colour, fillColor:colour, fillOpacity:0.8, weight:1 }})
      .bindTooltip(`${{emoji}} ${{f.properties[nameField]}}`).addTo(layer);
  }});
  return layer;
}}
L.control.layers({{}}, {{
  '🚂 Rail Stations': makeLayer(RAIL_DATA,  '#00ccff', 'stationName', '🚂'),
  '🚇 Tube Stations': makeLayer(TUBE_DATA,  '#ff00ff', 'NAME',        '🚇'),
  '🚌 Coach Stops':   makeLayer(COACH_DATA, '#00ff88', 'CommonName',  '🚌'),
}}, {{collapsed:false}}).addTo(map);

// ── Helpers ───────────────────────────────────────────────────
const delay = ms => new Promise(r => setTimeout(r, ms));

function haversine(lat1, lon1, lat2, lon2) {{
  const R = 6371;
  const dLat = (lat2-lat1)*Math.PI/180, dLon = (lon2-lon1)*Math.PI/180;
  const a = Math.sin(dLat/2)**2 + Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLon/2)**2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
}}

function findNearest(data, lat, lon) {{
  let best = null, bestDist = Infinity;
  data.features.forEach(f => {{
    const [flon, flat] = f.geometry.coordinates;
    const d = haversine(lat, lon, flat, flon);
    if (d < bestDist) {{ bestDist = d; best = f; }}
  }});
  return {{ feature: best, dist: bestDist.toFixed(2) }};
}}

async function getRoute(apiKey, fromLon, fromLat, toLon, toLat) {{
  try {{
    const res = await fetch('https://api.openrouteservice.org/v2/directions/driving-car/geojson', {{
      method:'POST',
      headers:{{'Authorization':apiKey,'Content-Type':'application/json'}},
      body: JSON.stringify({{coordinates:[[fromLon,fromLat],[toLon,toLat]]}})
    }});
    if (!res.ok) return null;
    const data = await res.json();
    const s = data.features[0].properties.summary;
    return {{
      mins: Math.round(s.duration/60),
      km:   (s.distance/1000).toFixed(1),
      coords: data.features[0].geometry.coordinates.map(c => [c[1],c[0]])
    }};
  }} catch(e) {{ return null; }}
}}

// ── Route state ───────────────────────────────────────────────
let routeLayers = [];
let startMarker = null;

function clearRoutes() {{
  routeLayers.forEach(l => map.removeLayer(l));
  routeLayers = [];
}}

function updateRow(id, leg1, leg2, colour, totalMins, totalKm) {{
  const el = document.getElementById(id);
  if (!el) return;
  const spinner = el.querySelector('.spinner');

  if (!leg1 && !leg2) {{
    if (spinner) spinner.outerHTML = '<div class="route-val" style="color:#ef4444">unavailable</div>';
    return;
  }}

  // Total time = leg1 + leg2
  const mins = totalMins;
  const km   = totalKm;
  if (spinner) spinner.outerHTML = `<div class="route-val done">${{mins}} min · ${{km}} km</div>`;

  // Draw leg1 (start → stop) as dashed
  const lines = [];
  if (leg1) {{
    const l1 = L.polyline(leg1.coords, {{
      color:colour, weight:3, opacity:0.9, dashArray:'8 5'
    }}).addTo(map);
    routeLayers.push(l1);
    lines.push(l1);
  }}

  // Draw leg2 (stop → airport) as solid
  if (leg2) {{
    const l2 = L.polyline(leg2.coords, {{
      color:colour, weight:4, opacity:0.9
    }}).addTo(map);
    routeLayers.push(l2);
    lines.push(l2);
  }}

  // Click to highlight
  el.onclick = () => {{
    routeLayers.forEach(l => l.setStyle({{opacity:0.15, weight:2}}));
    lines.forEach(l => l.setStyle({{opacity:1, weight:5}}));
    if (lines.length > 0) {{
      const allCoords = lines.flatMap(l => l.getLatLngs());
      map.fitBounds(L.latLngBounds(allCoords), {{padding:[40,40]}});
    }}
  }};
}}

// ── Main click handler ────────────────────────────────────────
map.on('click', async (e) => {{
  const {{ lat, lng }} = e.latlng;
  const apiKey = document.getElementById('apiKey').value.trim();

  document.getElementById('coords').textContent = `Start: ${{lat.toFixed(5)}}, ${{lng.toFixed(5)}}`;

  if (startMarker) map.removeLayer(startMarker);
  startMarker = L.circleMarker([lat, lng], {{
    radius:9, color:'#ff8800', fillColor:'#ff8800', fillOpacity:1, weight:2
  }}).addTo(map).bindPopup(`<b> Start point</b><br>${{lat.toFixed(5)}}, ${{lng.toFixed(5)}}`);

  clearRoutes();

  if (!apiKey) {{
    document.getElementById('results').innerHTML = '<div id="empty">Please enter your ORS API key above.</div>';
    return;
  }}

  const nearest = {{
    rail:  findNearest(RAIL_DATA,  lat, lng),
    tube:  findNearest(TUBE_DATA,  lat, lng),
    coach: findNearest(COACH_DATA, lat, lng),
  }};

  // Render loading skeleton
  const html = Object.entries(AIRPORTS).map(([code, ap]) => `
    <div class="airport-block">
      <div class="airport-header">
        <div class="dot" style="background:${{ap.colour}}"></div>
        ${{ap.name}} (${{code}})
      </div>
      <div class="route-row" id="r-${{code}}-drive">
        <div class="route-left">
          <div class="route-icon" style="background:#ff880033">🚗</div>
          <div class="route-label">Drive direct</div>
        </div><div class="spinner"></div>
      </div>
      <div class="route-row" id="r-${{code}}-rail">
        <div class="route-left">
          <div class="route-icon" style="background:#00ccff33">🚂</div>
          <div class="route-label">Rail<div class="route-sub">via ${{nearest.rail.feature.properties.stationName}} (${{nearest.rail.dist}} km)</div></div>
        </div><div class="spinner"></div>
      </div>
      <div class="route-row" id="r-${{code}}-tube">
        <div class="route-left">
          <div class="route-icon" style="background:#ff00ff33">🚇</div>
          <div class="route-label">Tube<div class="route-sub">via ${{nearest.tube.feature.properties.NAME}} (${{nearest.tube.dist}} km)</div></div>
        </div><div class="spinner"></div>
      </div>
      <div class="route-row" id="r-${{code}}-coach">
        <div class="route-left">
          <div class="route-icon" style="background:#00ff8833">🚌</div>
          <div class="route-label">Coach<div class="route-sub">via ${{nearest.coach.feature.properties.CommonName}} (${{nearest.coach.dist}} km)</div></div>
        </div><div class="spinner"></div>
      </div>
    </div>
  `).join('');
  document.getElementById('results').innerHTML = html;

  const lb = document.getElementById('loading-bar');
  lb.style.display = 'block';
  lb.style.color = '#f59e0b';
  lb.textContent = ' Loading routes... please wait (~20s)';

  // Fetch routes sequentially
  for (const [code, ap] of Object.entries(AIRPORTS)) {{
    const rn = nearest.rail.feature.geometry.coordinates;
    const tn = nearest.tube.feature.geometry.coordinates;
    const cn = nearest.coach.feature.geometry.coordinates;

    // Drive direct (single leg)
    const driveR = await getRoute(apiKey, lng, lat, ap.lon, ap.lat);
    if (driveR) updateRow(`r-${{code}}-drive`, driveR, null, ROUTE_COLOURS.drive, driveR.mins, driveR.km);
    else updateRow(`r-${{code}}-drive`, null, null, ROUTE_COLOURS.drive, 0, 0);
    await delay(1600);

    // Rail: leg1 = start→station, leg2 = station→airport
    const railL1 = await getRoute(apiKey, lng, lat, rn[0], rn[1]);
    await delay(1600);
    const railL2 = await getRoute(apiKey, rn[0], rn[1], ap.lon, ap.lat);
    const railMins = (railL1?.mins||0) + (railL2?.mins||0);
    const railKm   = ((parseFloat(railL1?.km)||0) + (parseFloat(railL2?.km)||0)).toFixed(1);
    updateRow(`r-${{code}}-rail`, railL1, railL2, ROUTE_COLOURS.rail, railMins, railKm);
    await delay(1600);

    // Tube: leg1 = start→tube station, leg2 = tube station→airport
    const tubeL1 = await getRoute(apiKey, lng, lat, tn[0], tn[1]);
    await delay(1600);
    const tubeL2 = await getRoute(apiKey, tn[0], tn[1], ap.lon, ap.lat);
    const tubeMins = (tubeL1?.mins||0) + (tubeL2?.mins||0);
    const tubeKm   = ((parseFloat(tubeL1?.km)||0) + (parseFloat(tubeL2?.km)||0)).toFixed(1);
    updateRow(`r-${{code}}-tube`, tubeL1, tubeL2, ROUTE_COLOURS.tube, tubeMins, tubeKm);
    await delay(1600);

    // Coach: leg1 = start→coach stop, leg2 = coach stop→airport
    const coachL1 = await getRoute(apiKey, lng, lat, cn[0], cn[1]);
    await delay(1600);
    const coachL2 = await getRoute(apiKey, cn[0], cn[1], ap.lon, ap.lat);
    const coachMins = (coachL1?.mins||0) + (coachL2?.mins||0);
    const coachKm   = ((parseFloat(coachL1?.km)||0) + (parseFloat(coachL2?.km)||0)).toFixed(1);
    updateRow(`r-${{code}}-coach`, coachL1, coachL2, ROUTE_COLOURS.coach, coachMins, coachKm);
    await delay(1600);
  }}

  lb.textContent = '✓ All routes loaded — click a row to highlight';
  lb.style.color = '#22c55e';
}});
</script>
</body>
</html>"""

output_path = '/content/drive/MyDrive/airport_journey_planner_v4.html'
with open(output_path, 'w') as f:
    f.write(html_content)

print(' Saved to Google Drive as airport_journey_planner_v4.html')
print('  Download and open in Chrome/Edge')
print('  Routes now show FULL journey: start → stop → airport')
print('  Dashed line = to nearest stop, Solid line = stop → airport')

coach_df_wide = pd.read_excel('/content/Transport.updated.xlsx')

# Wider filter — extend north to 54.0 to cover full catchment
coach_df_wide = coach_df_wide[
    (coach_df_wide['Latitude']  >= 51.0) &
    (coach_df_wide['Latitude']  <= 54.0) &  # extended from 53.5
    (coach_df_wide['Longitude'] >= -3.0) &  # extended west slightly
    (coach_df_wide['Longitude'] <= 0.5)  &
    (coach_df_wide['StopType']  == 'BCT')
].copy()

# Convert to GeoDataFrame
coach_gdf_wide = gpd.GeoDataFrame(
    coach_df_wide,
    geometry=gpd.points_from_xy(coach_df_wide['Longitude'], coach_df_wide['Latitude']),
    crs='EPSG:4326'
)

# Spatial join to catchment only
from shapely.ops import unary_union
from shapely.geometry import shape

all_polys = []
for iata in ['LHR', 'LGW', 'LTN']:
    features = all_isochrones[iata]['features']
    geom = shape(features[-1]['geometry'])
    all_polys.append(geom)

combined = unary_union(all_polys)
combined_gdf = gpd.GeoDataFrame(geometry=[combined], crs='EPSG:4326')

coach_in_catchment_wide = gpd.sjoin(
    coach_gdf_wide,
    combined_gdf,
    how='inner',
    predicate='within'
).drop(columns=['index_right'], errors='ignore')

# Deduplicate
coach_dedup_wide = coach_in_catchment_wide.drop_duplicates(subset=['CommonName']).copy()
coach_dedup_wide = coach_dedup_wide.reset_index(drop=True)

# Check by band
coach_dedup_wide['lat_band'] = pd.cut(
    coach_dedup_wide.geometry.y,
    bins=[51.0, 51.5, 52.0, 52.5, 53.0, 53.5, 54.0],
    labels=['51-51.5', '51.5-52', '52-52.5', '52.5-53', '53-53.5', '53.5-54']
)

print(f' Total coach stops: {len(coach_dedup_wide)}')
print('\nCoach stops by latitude band:')
print(coach_dedup_wide['lat_band'].value_counts().sort_index())

# Sample to keep map performant but with better coverage
# Keep all stops north of 52.0 (sparse area) + 10% sample south of 52.0
north = coach_dedup_wide[coach_dedup_wide.geometry.y >= 52.0].copy()
south = coach_dedup_wide[coach_dedup_wide.geometry.y <  52.0].sample(frac=0.15, random_state=42).copy()

coach_final = pd.concat([north, south]).reset_index(drop=True)

print(f'North of 52.0: {len(north)} stops (all kept)')
print(f'South of 52.0: {len(south)} stops (15% sample)')
print(f'Total: {len(coach_final)} stops')

# Update coach_json with the better coverage dataset
coach_json_wide = json.loads(
    coach_final[['CommonName', 'geometry']].to_json()
)

print(f' Coach JSON ready: {len(coach_final)} stops')
print('  Regenerating HTML')

"""had to add more coach stops, because before there was none further up St. Albans"""

html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>London Airport Catchment — Interactive Journey Planner</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js"></script>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family: Arial, sans-serif; height:100vh; display:flex; flex-direction:column; }}
  #header {{ background:#1a1a2e; color:white; padding:10px 20px; display:flex; align-items:center; justify-content:space-between; flex-shrink:0; }}
  #header h1 {{ font-size:14px; font-weight:bold; letter-spacing:0.05em; }}
  #api-bar {{ background:#0d1525; padding:6px 20px; display:flex; align-items:center; gap:10px; flex-shrink:0; border-bottom:1px solid #2a3a50; }}
  #api-bar label {{ font-size:11px; color:#888; white-space:nowrap; }}
  #api-bar input {{ flex:1; background:#1e2d45; border:1px solid #2a3a50; color:white; padding:4px 8px; font-size:11px; border-radius:3px; }}
  #main {{ display:flex; flex:1; overflow:hidden; }}
  #map {{ flex:1; }}
  #sidebar {{ width:340px; background:#111827; color:#e2e8f0; display:flex; flex-direction:column; overflow:hidden; border-left:1px solid #1e2d45; flex-shrink:0; }}
  #sidebar-title {{ padding:12px 16px; border-bottom:1px solid #1e2d45; font-size:12px; font-weight:bold; text-transform:uppercase; letter-spacing:0.08em; color:#94a3b8; }}
  #instruction {{ padding:10px 16px; border-bottom:1px solid #1e2d45; font-size:11px; color:#64748b; line-height:1.5; }}
  #results {{ flex:1; overflow-y:auto; padding:10px; }}
  .airport-block {{ margin-bottom:10px; border:1px solid #1e2d45; border-radius:6px; overflow:hidden; }}
  .airport-header {{ padding:8px 12px; display:flex; align-items:center; gap:8px; border-bottom:1px solid #1e2d45; font-size:12px; font-weight:bold; }}
  .dot {{ width:8px; height:8px; border-radius:50%; flex-shrink:0; }}
  .route-row {{ padding:7px 12px; display:flex; align-items:center; justify-content:space-between; border-bottom:1px solid #1e2d45; font-size:11px; cursor:pointer; transition:background 0.1s; }}
  .route-row:last-child {{ border-bottom:none; }}
  .route-row:hover {{ background:rgba(255,255,255,0.04); }}
  .route-left {{ display:flex; align-items:center; gap:8px; }}
  .route-icon {{ width:20px; height:20px; border-radius:3px; display:flex; align-items:center; justify-content:center; font-size:11px; flex-shrink:0; }}
  .route-label {{ font-size:11px; line-height:1.3; }}
  .route-sub {{ font-size:9px; color:#64748b; }}
  .route-val {{ color:#94a3b8; font-size:11px; white-space:nowrap; }}
  .route-val.done {{ color:#e2e8f0; }}
  .spinner {{ width:11px; height:11px; border:2px solid #1e2d45; border-top-color:#64748b; border-radius:50%; animation:spin 0.7s linear infinite; flex-shrink:0; }}
  @keyframes spin {{ to {{ transform:rotate(360deg); }} }}
  #empty {{ padding:30px 16px; text-align:center; font-size:11px; color:#64748b; line-height:1.7; }}
  #coords {{ padding:5px 16px; border-top:1px solid #1e2d45; font-size:10px; color:#475569; }}
  #legend {{ padding:8px 16px; border-top:1px solid #1e2d45; display:flex; flex-wrap:wrap; gap:8px; }}
  .leg {{ display:flex; align-items:center; gap:4px; font-size:10px; color:#64748b; }}
  .leg-line {{ width:16px; height:3px; border-radius:1px; }}
  #loading-bar {{ padding:6px 16px; font-size:10px; color:#f59e0b; display:none; border-top:1px solid #1e2d45; }}
  .leaflet-popup-content-wrapper {{ background:#1e2d45; color:#e2e8f0; font-family:Arial; font-size:11px; border-radius:5px; }}
  .leaflet-popup-tip {{ background:#1e2d45; }}
</style>
</head>
<body>

<div id="header">
  <h1>✈ London Airport Catchment — Interactive Journey Planner</h1>
  <span style="font-size:11px;color:#64748b;">University of Westminster · SAC Project</span>
</div>

<div id="api-bar">
  <label>ORS API KEY:</label>
  <input type="password" id="apiKey" placeholder="Paste your OpenRouteService API key…"/>
</div>

<div id="main">
  <div id="map"></div>
  <div id="sidebar">
    <div id="sidebar-title">Journey Routes</div>
    <div id="instruction">
      Click anywhere on the map to calculate routes to all three airports.<br><br>
      Transport routes show the <b>full journey</b>: start → nearest stop → airport.
      Click any row to highlight that route.
    </div>
    <div id="results">
      <div id="empty">Click anywhere on the map<br>to calculate journey times.</div>
    </div>
    <div id="loading-bar">⏳ Loading routes... please wait (~20s)</div>
    <div id="legend">
      <div class="leg"><div class="leg-line" style="background:#ff8800"></div>Drive</div>
      <div class="leg"><div class="leg-line" style="background:#00ccff"></div>Rail</div>
      <div class="leg"><div class="leg-line" style="background:#ff00ff"></div>Tube</div>
      <div class="leg"><div class="leg-line" style="background:#00ff88"></div>Coach</div>
    </div>
    <div id="coords">Coordinates: —</div>
  </div>
</div>

<script>
const ISO_DATA   = {json.dumps(iso_geojson)};
const RAIL_DATA  = {json.dumps(rail_json)};
const TUBE_DATA  = {json.dumps(tube_json)};
const COACH_DATA = {json.dumps(coach_json_wide)};
const ITL3_DATA  = {json.dumps(itl3_json)};

const AIRPORTS = {{
  LHR: {{ name:'London Heathrow', lat:51.4706, lon:-0.4541, colour:'#3b82f6' }},
  LGW: {{ name:'London Gatwick',  lat:51.1564, lon:-0.1622, colour:'#ef4444' }},
  LTN: {{ name:'London Luton',    lat:51.8796, lon:-0.3713, colour:'#22c55e' }},
}};

const ROUTE_COLOURS = {{
  drive: '#ff8800',
  rail:  '#00ccff',
  tube:  '#ff00ff',
  coach: '#00ff88',
}};

const isoColours = {{ LHR:'#3b82f6', LGW:'#ef4444', LTN:'#22c55e' }};
const TIMES = [30, 45, 60];

// ── Map ───────────────────────────────────────────────────────
const map = L.map('map').setView([51.5, -0.3], 8);
L.tileLayer('https://{{s}}.basemaps.cartocdn.com/dark_all/{{z}}/{{x}}/{{y}}{{r}}.png', {{
  attribution:'© OpenStreetMap © CARTO', maxZoom:18
}}).addTo(map);

// ── ITL3 choropleth ───────────────────────────────────────────
const pops = ITL3_DATA.features.map(f => f.properties.population_2024 || 0);
const minPop = Math.min(...pops), maxPop = Math.max(...pops);
function popColour(pop) {{
  if (!pop) return '#374151';
  const t = (pop - minPop) / (maxPop - minPop);
  const r = Math.round(255 * Math.min(1, t * 2));
  const g = Math.round(255 * Math.max(0, 1 - t * 2));
  return `rgb(${{r}},${{g}},50)`;
}}
L.geoJSON(ITL3_DATA, {{
  style: f => ({{ fillColor: popColour(f.properties.population_2024), color:'#374151', weight:0.5, fillOpacity:0.5 }}),
  onEachFeature: (f, layer) => {{
    const p = f.properties;
    layer.bindTooltip(
      `<b>${{p.ITL321NM}}</b><br>Population: ${{(p.population_2024||0).toLocaleString()}}<br>GDHI: £${{(p.GDHI_2023_million_gbp||0).toLocaleString()}}M`,
      {{sticky:true}}
    );
  }}
}}).addTo(map);

// ── Isochrones ────────────────────────────────────────────────
Object.entries(ISO_DATA).forEach(([iata, geojson]) => {{
  geojson.features.forEach((feature, i) => {{
    L.geoJSON(feature, {{ style: {{ color:isoColours[iata], weight:[2.5,1.8,1.2][i], fillOpacity:0, opacity:0.9 }} }})
      .bindTooltip(`${{iata}} — ${{TIMES[i]}} min drive`).addTo(map);
  }});
}});

// ── Airport markers ───────────────────────────────────────────
Object.entries(AIRPORTS).forEach(([code, ap]) => {{
  L.marker([ap.lat, ap.lon], {{
    icon: L.divIcon({{
      html:`<div style="background:${{ap.colour}};color:white;border-radius:50%;width:32px;height:32px;
            display:flex;align-items:center;justify-content:center;font-size:9px;font-weight:bold;
            border:2px solid rgba(255,255,255,0.4);box-shadow:0 0 10px ${{ap.colour}}88;">✈${{code}}</div>`,
      className:'', iconSize:[32,32], iconAnchor:[16,16]
    }})
  }}).addTo(map).bindPopup(`<b>✈ ${{ap.name}}</b><br>${{code}}`);
}});

// ── Transport layers ──────────────────────────────────────────
function makeLayer(data, colour, nameField, emoji) {{
  const layer = L.layerGroup();
  data.features.forEach(f => {{
    const [lon, lat] = f.geometry.coordinates;
    L.circleMarker([lat, lon], {{
      radius:4, color:colour, fillColor:colour, fillOpacity:0.8, weight:1
    }}).bindTooltip(`${{emoji}} ${{f.properties[nameField]}}`).addTo(layer);
  }});
  return layer;
}}
L.control.layers({{}}, {{
  '🚂 Rail Stations': makeLayer(RAIL_DATA,  '#00ccff', 'stationName', '🚂'),
  '🚇 Tube Stations': makeLayer(TUBE_DATA,  '#ff00ff', 'NAME',        '🚇'),
  '🚌 Coach Stops':   makeLayer(COACH_DATA, '#00ff88', 'CommonName',  '🚌'),
}}, {{collapsed:false}}).addTo(map);

// ── Helpers ───────────────────────────────────────────────────
const delay = ms => new Promise(r => setTimeout(r, ms));

function haversine(lat1, lon1, lat2, lon2) {{
  const R = 6371;
  const dLat = (lat2-lat1)*Math.PI/180, dLon = (lon2-lon1)*Math.PI/180;
  const a = Math.sin(dLat/2)**2 +
    Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLon/2)**2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
}}

function findNearest(data, lat, lon) {{
  let best = null, bestDist = Infinity;
  data.features.forEach(f => {{
    const [flon, flat] = f.geometry.coordinates;
    const d = haversine(lat, lon, flat, flon);
    if (d < bestDist) {{ bestDist = d; best = f; }}
  }});
  return {{ feature: best, dist: bestDist.toFixed(2) }};
}}

async function getRoute(apiKey, fromLon, fromLat, toLon, toLat) {{
  try {{
    const res = await fetch(
      'https://api.openrouteservice.org/v2/directions/driving-car/geojson',
      {{
        method:'POST',
        headers:{{'Authorization':apiKey,'Content-Type':'application/json'}},
        body: JSON.stringify({{coordinates:[[fromLon,fromLat],[toLon,toLat]]}})
      }}
    );
    if (!res.ok) return null;
    const data = await res.json();
    const s = data.features[0].properties.summary;
    return {{
      mins: Math.round(s.duration/60),
      km:   (s.distance/1000).toFixed(1),
      coords: data.features[0].geometry.coordinates.map(c => [c[1],c[0]])
    }};
  }} catch(e) {{ return null; }}
}}

// ── Route state ───────────────────────────────────────────────
let routeLayers = [];
let startMarker = null;

function clearRoutes() {{
  routeLayers.forEach(l => map.removeLayer(l));
  routeLayers = [];
}}

function updateRow(id, leg1, leg2, colour, totalMins, totalKm) {{
  const el = document.getElementById(id);
  if (!el) return;
  const spinner = el.querySelector('.spinner');
  if (!leg1 && !leg2) {{
    if (spinner) spinner.outerHTML = '<div class="route-val" style="color:#ef4444">unavailable</div>';
    return;
  }}
  if (spinner) spinner.outerHTML = `<div class="route-val done">${{totalMins}} min · ${{totalKm}} km</div>`;
  const lines = [];
  if (leg1) {{
    const l1 = L.polyline(leg1.coords, {{ color:colour, weight:3, opacity:0.9, dashArray:'8 5' }}).addTo(map);
    routeLayers.push(l1);
    lines.push(l1);
  }}
  if (leg2) {{
    const l2 = L.polyline(leg2.coords, {{ color:colour, weight:4, opacity:0.9 }}).addTo(map);
    routeLayers.push(l2);
    lines.push(l2);
  }}
  el.onclick = () => {{
    routeLayers.forEach(l => l.setStyle({{opacity:0.15, weight:2}}));
    lines.forEach(l => l.setStyle({{opacity:1, weight:5}}));
    if (lines.length > 0) {{
      const allCoords = lines.flatMap(l => l.getLatLngs());
      map.fitBounds(L.latLngBounds(allCoords), {{padding:[40,40]}});
    }}
  }};
}}

// ── Click handler ─────────────────────────────────────────────
map.on('click', async (e) => {{
  const {{ lat, lng }} = e.latlng;
  const apiKey = document.getElementById('apiKey').value.trim();

  document.getElementById('coords').textContent =
    `Start: ${{lat.toFixed(5)}}, ${{lng.toFixed(5)}}`;

  if (startMarker) map.removeLayer(startMarker);
  startMarker = L.circleMarker([lat, lng], {{
    radius:9, color:'#ff8800', fillColor:'#ff8800', fillOpacity:1, weight:2
  }}).addTo(map).bindPopup(`<b>📍 Start point</b><br>${{lat.toFixed(5)}}, ${{lng.toFixed(5)}}`);

  clearRoutes();

  if (!apiKey) {{
    document.getElementById('results').innerHTML =
      '<div id="empty">Please enter your ORS API key above.</div>';
    return;
  }}

  const nearest = {{
    rail:  findNearest(RAIL_DATA,  lat, lng),
    tube:  findNearest(TUBE_DATA,  lat, lng),
    coach: findNearest(COACH_DATA, lat, lng),
  }};

  const html = Object.entries(AIRPORTS).map(([code, ap]) => `
    <div class="airport-block">
      <div class="airport-header">
        <div class="dot" style="background:${{ap.colour}}"></div>
        ${{ap.name}} (${{code}})
      </div>
      <div class="route-row" id="r-${{code}}-drive">
        <div class="route-left">
          <div class="route-icon" style="background:#ff880033">🚗</div>
          <div class="route-label">Drive direct</div>
        </div><div class="spinner"></div>
      </div>
      <div class="route-row" id="r-${{code}}-rail">
        <div class="route-left">
          <div class="route-icon" style="background:#00ccff33">🚂</div>
          <div class="route-label">Rail
            <div class="route-sub">via ${{nearest.rail.feature.properties.stationName}} (${{nearest.rail.dist}} km)</div>
          </div>
        </div><div class="spinner"></div>
      </div>
      <div class="route-row" id="r-${{code}}-tube">
        <div class="route-left">
          <div class="route-icon" style="background:#ff00ff33">🚇</div>
          <div class="route-label">Tube
            <div class="route-sub">via ${{nearest.tube.feature.properties.NAME}} (${{nearest.tube.dist}} km)</div>
          </div>
        </div><div class="spinner"></div>
      </div>
      <div class="route-row" id="r-${{code}}-coach">
        <div class="route-left">
          <div class="route-icon" style="background:#00ff8833">🚌</div>
          <div class="route-label">Coach
            <div class="route-sub">via ${{nearest.coach.feature.properties.CommonName}} (${{nearest.coach.dist}} km)</div>
          </div>
        </div><div class="spinner"></div>
      </div>
    </div>
  `).join('');
  document.getElementById('results').innerHTML = html;

  const lb = document.getElementById('loading-bar');
  lb.style.display = 'block';
  lb.style.color = '#f59e0b';
  lb.textContent = ' Loading routes... please wait (~20s)';

  for (const [code, ap] of Object.entries(AIRPORTS)) {{
    const rn = nearest.rail.feature.geometry.coordinates;
    const tn = nearest.tube.feature.geometry.coordinates;
    const cn = nearest.coach.feature.geometry.coordinates;

    const driveR = await getRoute(apiKey, lng, lat, ap.lon, ap.lat);
    updateRow(`r-${{code}}-drive`, driveR, null, ROUTE_COLOURS.drive, driveR?.mins||0, driveR?.km||0);
    await delay(1600);

    const railL1 = await getRoute(apiKey, lng, lat, rn[0], rn[1]);
    await delay(1600);
    const railL2 = await getRoute(apiKey, rn[0], rn[1], ap.lon, ap.lat);
    updateRow(`r-${{code}}-rail`, railL1, railL2, ROUTE_COLOURS.rail,
      (railL1?.mins||0)+(railL2?.mins||0),
      ((parseFloat(railL1?.km)||0)+(parseFloat(railL2?.km)||0)).toFixed(1));
    await delay(1600);

    const tubeL1 = await getRoute(apiKey, lng, lat, tn[0], tn[1]);
    await delay(1600);
    const tubeL2 = await getRoute(apiKey, tn[0], tn[1], ap.lon, ap.lat);
    updateRow(`r-${{code}}-tube`, tubeL1, tubeL2, ROUTE_COLOURS.tube,
      (tubeL1?.mins||0)+(tubeL2?.mins||0),
      ((parseFloat(tubeL1?.km)||0)+(parseFloat(tubeL2?.km)||0)).toFixed(1));
    await delay(1600);

    const coachL1 = await getRoute(apiKey, lng, lat, cn[0], cn[1]);
    await delay(1600);
    const coachL2 = await getRoute(apiKey, cn[0], cn[1], ap.lon, ap.lat);
    updateRow(`r-${{code}}-coach`, coachL1, coachL2, ROUTE_COLOURS.coach,
      (coachL1?.mins||0)+(coachL2?.mins||0),
      ((parseFloat(coachL1?.km)||0)+(parseFloat(coachL2?.km)||0)).toFixed(1));
    await delay(1600);
  }}

  lb.textContent = '✓ All routes loaded — click a row to highlight';
  lb.style.color = '#22c55e';
}});
</script>
</body>
</html>"""

output_path = '/content/drive/MyDrive/airport_journey_planner_v5.html'
with open(output_path, 'w') as f:
    f.write(html_content)

print(' Saved: airport_journey_planner_v5.html')
print('  Download from Drive and open in Chrome/Edge')

"""working on the google street interactive map"""

html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>London Airport Catchment — Journey Planner</title>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family:Arial,sans-serif; height:100vh; display:flex; flex-direction:column; }}
  #header {{ background:#1a1a2e; color:white; padding:10px 20px; display:flex; align-items:center; justify-content:space-between; flex-shrink:0; }}
  #header h1 {{ font-size:14px; font-weight:bold; }}
  #api-bar {{ background:#0d1525; padding:6px 20px; display:flex; align-items:center; gap:10px; flex-shrink:0; border-bottom:1px solid #2a3a50; }}
  #api-bar label {{ font-size:11px; color:#888; white-space:nowrap; }}
  #api-bar input {{ flex:1; background:#1e2d45; border:1px solid #2a3a50; color:white; padding:4px 8px; font-size:11px; border-radius:3px; }}
  #api-bar button {{ background:#3b82f6; color:white; border:none; padding:5px 14px; font-size:11px; border-radius:3px; cursor:pointer; white-space:nowrap; }}
  #api-bar button:hover {{ background:#2563eb; }}
  #main {{ display:flex; flex:1; overflow:hidden; }}
  #map {{ flex:1; background:#0a0e1a; display:none; }}
  #map-placeholder {{ flex:1; background:#0a0e1a; display:flex; align-items:center; justify-content:center; color:#475569; font-size:13px; flex-direction:column; gap:8px; }}
  #sidebar {{ width:340px; background:#111827; color:#e2e8f0; display:flex; flex-direction:column; overflow:hidden; border-left:1px solid #1e2d45; flex-shrink:0; }}
  #sidebar-title {{ padding:12px 16px; border-bottom:1px solid #1e2d45; font-size:12px; font-weight:bold; text-transform:uppercase; letter-spacing:0.08em; color:#94a3b8; }}
  #instruction {{ padding:10px 16px; border-bottom:1px solid #1e2d45; font-size:11px; color:#64748b; line-height:1.5; }}
  #results {{ flex:1; overflow-y:auto; padding:10px; }}
  .airport-block {{ margin-bottom:10px; border:1px solid #1e2d45; border-radius:6px; overflow:hidden; }}
  .airport-header {{ padding:8px 12px; display:flex; align-items:center; gap:8px; border-bottom:1px solid #1e2d45; font-size:12px; font-weight:bold; }}
  .dot {{ width:8px; height:8px; border-radius:50%; flex-shrink:0; }}
  .route-row {{ padding:7px 12px; display:flex; align-items:center; justify-content:space-between; border-bottom:1px solid #1e2d45; font-size:11px; cursor:pointer; transition:background 0.1s; }}
  .route-row:last-child {{ border-bottom:none; }}
  .route-row:hover {{ background:rgba(255,255,255,0.04); }}
  .route-left {{ display:flex; align-items:center; gap:8px; }}
  .route-icon {{ width:20px; height:20px; border-radius:3px; display:flex; align-items:center; justify-content:center; font-size:11px; flex-shrink:0; }}
  .route-label {{ font-size:11px; line-height:1.3; }}
  .route-sub {{ font-size:9px; color:#64748b; }}
  .route-val {{ color:#94a3b8; font-size:11px; white-space:nowrap; }}
  .route-val.done {{ color:#e2e8f0; font-weight:bold; }}
  .spinner {{ width:11px; height:11px; border:2px solid #1e2d45; border-top-color:#64748b; border-radius:50%; animation:spin 0.7s linear infinite; flex-shrink:0; }}
  @keyframes spin {{ to {{ transform:rotate(360deg); }} }}
  #empty {{ padding:30px 16px; text-align:center; font-size:11px; color:#64748b; line-height:1.7; }}
  #coords {{ padding:5px 16px; border-top:1px solid #1e2d45; font-size:10px; color:#475569; }}
  #legend {{ padding:8px 16px; border-top:1px solid #1e2d45; display:flex; flex-wrap:wrap; gap:8px; }}
  .leg {{ display:flex; align-items:center; gap:4px; font-size:10px; color:#64748b; }}
  .leg-line {{ width:16px; height:3px; border-radius:1px; }}
  #loading-bar {{ padding:6px 16px; font-size:10px; color:#f59e0b; display:none; border-top:1px solid #1e2d45; }}
</style>
</head>
<body>

<div id="header">
  <h1>✈ London Airport Catchment — Interactive Journey Planner</h1>
  <span style="font-size:11px;color:#64748b;">University of Westminster · SAC Project</span>
</div>

<div id="api-bar">
  <label>GOOGLE MAPS KEY:</label>
  <input type="password" id="apiKey" placeholder="Paste your Google Maps API key here…"/>
  <button onclick="loadMap()">Load Map</button>
</div>

<div id="main">
  <div id="map-placeholder">
    <div style="font-size:32px">🗺</div>
    <div>Enter your Google Maps API key above and click Load Map</div>
  </div>
  <div id="map"></div>
  <div id="sidebar">
    <div id="sidebar-title">Journey Routes</div>
    <div id="instruction">
      Enter your API key and click Load Map.<br><br>
      Then click anywhere on the map to calculate real journey times to all three airports via Drive and Transit (real train/tube/bus routes).
    </div>
    <div id="results">
      <div id="empty">Load the map first then<br>click anywhere to begin.</div>
    </div>
    <div id="loading-bar">⏳ Calculating routes...</div>
    <div id="legend">
      <div class="leg"><div class="leg-line" style="background:#ff8800"></div>Drive</div>
      <div class="leg"><div class="leg-line" style="background:#00ccff"></div>Transit</div>
    </div>
    <div id="coords">Coordinates: —</div>
  </div>
</div>

<script>
const AIRPORTS = {{
  LHR: {{ name:'London Heathrow', lat:51.4706, lng:-0.4541, colour:'#3b82f6' }},
  LGW: {{ name:'London Gatwick',  lat:51.1564, lng:-0.1622, colour:'#ef4444' }},
  LTN: {{ name:'London Luton',    lat:51.8796, lng:-0.3713, colour:'#22c55e' }},
}};

const ROUTE_COLOURS = {{
  DRIVING: '#ff8800',
  TRANSIT: '#00ccff',
}};

const ISO_DATA  = {json.dumps(iso_geojson)};
const ITL3_DATA = {json.dumps(itl3_json)};

let map, directionsService;
let startMarker = null;
let renderers   = [];
let mapLoaded   = false;

function loadMap() {{
  const key = document.getElementById('apiKey').value.trim();
  if (!key) {{ alert('Please enter your Google Maps API key first.'); return; }}
  if (mapLoaded) {{ alert('Map already loaded!'); return; }}
  document.getElementById('map-placeholder').style.display = 'none';
  document.getElementById('map').style.display = 'block';
  const script = document.createElement('script');
  script.src = `https://maps.googleapis.com/maps/api/js?key=${{key}}&callback=initMap`;
  script.async = true;
  script.defer = true;
  document.head.appendChild(script);
  mapLoaded = true;
}}

function initMap() {{
  map = new google.maps.Map(document.getElementById('map'), {{
    center: {{ lat:51.5, lng:-0.3 }},
    zoom: 8,
    mapTypeId: 'roadmap',
    styles: [
      {{ elementType:'geometry', stylers:[{{color:'#1a1a2e'}}] }},
      {{ elementType:'labels.text.fill', stylers:[{{color:'#94a3b8'}}] }},
      {{ elementType:'labels.text.stroke', stylers:[{{color:'#1a1a2e'}}] }},
      {{ featureType:'road', elementType:'geometry', stylers:[{{color:'#2d3748'}}] }},
      {{ featureType:'road.highway', elementType:'geometry', stylers:[{{color:'#2d4a7a'}}] }},
      {{ featureType:'water', elementType:'geometry', stylers:[{{color:'#0d1525'}}] }},
      {{ featureType:'transit.line', elementType:'geometry', stylers:[{{color:'#4a5568'}}] }},
      {{ featureType:'transit.station', elementType:'geometry', stylers:[{{color:'#374151'}}] }},
      {{ featureType:'poi', stylers:[{{visibility:'off'}}] }},
    ]
  }});

  directionsService = new google.maps.DirectionsService();

  // ── ITL3 choropleth — clickable:false so clicks pass through ─
  const pops   = ITL3_DATA.features.map(f => f.properties.population_2024 || 0);
  const minPop = Math.min(...pops), maxPop = Math.max(...pops);

  function popColour(pop) {{
    if (!pop) return '#374151';
    const t = (pop - minPop) / (maxPop - minPop);
    const r = Math.round(255 * Math.min(1, t * 2));
    const g = Math.round(255 * Math.max(0, 1 - t * 2));
    return `rgb(${{r}},${{g}},50)`;
  }}

  const infoWindow = new google.maps.InfoWindow();

  ITL3_DATA.features.forEach(f => {{
    if (!f.geometry?.coordinates) return;
    const coords = f.geometry.coordinates[0].map(c => ({{lat:c[1], lng:c[0]}}));
    const poly = new google.maps.Polygon({{
      paths:        coords,
      strokeColor:  '#374151',
      strokeWeight: 0.5,
      fillColor:    popColour(f.properties.population_2024),
      fillOpacity:  0.5,
      clickable:    false,
      map:          map
    }});
  }});

  // Isochrone outlines — also non-clickable
  const isoColours = {{ LHR:'#3b82f6', LGW:'#ef4444', LTN:'#22c55e' }};
  const isoWeights = [3, 2, 1.5];

  Object.entries(ISO_DATA).forEach(([iata, geojson]) => {{
    geojson.features.forEach((feature, i) => {{
      const coords = feature.geometry.coordinates[0].map(c => ({{lat:c[1], lng:c[0]}}));
      new google.maps.Polygon({{
        paths:         coords,
        strokeColor:   isoColours[iata],
        strokeWeight:  isoWeights[i],
        strokeOpacity: 0.9,
        fillOpacity:   0,
        clickable:     false,
        map:           map
      }});
    }});
  }});

  // Airport markers
  Object.entries(AIRPORTS).forEach(([code, ap]) => {{
    const marker = new google.maps.Marker({{
      position: {{ lat:ap.lat, lng:ap.lng }},
      map:      map,
      title:    ap.name,
      label:    {{ text:'✈', color:'white', fontSize:'12px' }},
      icon: {{
        path:        google.maps.SymbolPath.CIRCLE,
        scale:       14,
        fillColor:   ap.colour,
        fillOpacity: 1,
        strokeColor: 'white',
        strokeWeight:2,
      }}
    }});
    const iw = new google.maps.InfoWindow({{content:`<b>✈ ${{ap.name}}</b><br>${{code}}`}});
    marker.addListener('click', () => iw.open(map, marker));
  }});

  // Click handler
  map.addListener('click', e => {{
    const lat = e.latLng.lat();
    const lng = e.latLng.lng();
    document.getElementById('coords').textContent =
      `Start: ${{lat.toFixed(5)}}, ${{lng.toFixed(5)}}`;
    if (startMarker) startMarker.setMap(null);
    startMarker = new google.maps.Marker({{
      position: {{ lat, lng }},
      map:      map,
      title:    'Start point',
      icon: {{
        path:        google.maps.SymbolPath.CIRCLE,
        scale:       10,
        fillColor:   '#ff8800',
        fillOpacity: 1,
        strokeColor: 'white',
        strokeWeight:2,
      }}
    }});
    clearRoutes();
    calculateAllRoutes(lat, lng);
  }});

  document.getElementById('empty').textContent =
    'Click anywhere on the map to calculate journey times.';
}}

function clearRoutes() {{
  renderers.forEach(r => r.setMap(null));
  renderers = [];
}}

function calculateAllRoutes(lat, lng) {{
  const lb = document.getElementById('loading-bar');
  lb.style.display = 'block';
  lb.style.color   = '#f59e0b';
  lb.textContent   = '⏳ Calculating routes...';

  const html = Object.entries(AIRPORTS).map(([code, ap]) => `
    <div class="airport-block">
      <div class="airport-header">
        <div class="dot" style="background:${{ap.colour}}"></div>
        ${{ap.name}} (${{code}})
      </div>
      <div class="route-row" id="r-${{code}}-DRIVING">
        <div class="route-left">
          <div class="route-icon" style="background:#ff880033">🚗</div>
          <div class="route-label">Drive direct</div>
        </div><div class="spinner"></div>
      </div>
      <div class="route-row" id="r-${{code}}-TRANSIT">
        <div class="route-left">
          <div class="route-icon" style="background:#00ccff33">🚆</div>
          <div class="route-label">Transit<div class="route-sub">Train · Tube · Bus</div></div>
        </div><div class="spinner"></div>
      </div>
    </div>
  `).join('');
  document.getElementById('results').innerHTML = html;

  let completed = 0;
  const total   = Object.keys(AIRPORTS).length * 2;

  Object.entries(AIRPORTS).forEach(([code, ap]) => {{
    ['DRIVING', 'TRANSIT'].forEach(mode => {{
      const renderer = new google.maps.DirectionsRenderer({{
        suppressMarkers: true,
        polylineOptions: {{
          strokeColor:   ROUTE_COLOURS[mode],
          strokeWeight:  mode === 'DRIVING' ? 5 : 4,
          strokeOpacity: 0.85,
        }}
      }});
      renderers.push(renderer);

      directionsService.route({{
        origin:      {{ lat, lng }},
        destination: {{ lat:ap.lat, lng:ap.lng }},
        travelMode:  google.maps.TravelMode[mode],
        ...(mode === 'TRANSIT' ? {{
          transitOptions: {{
            departureTime: new Date(),
            modes: [
              google.maps.TransitMode.RAIL,
              google.maps.TransitMode.SUBWAY,
              google.maps.TransitMode.BUS
            ],
            routingPreference: google.maps.TransitRoutePreference.FEWER_TRANSFERS
          }}
        }} : {{}})
      }}, (result, status) => {{
        completed++;
        const el = document.getElementById(`r-${{code}}-${{mode}}`);

        if (status === 'OK') {{
          renderer.setMap(map);
          renderer.setDirections(result);
          const leg  = result.routes[0].legs[0];
          const mins = Math.round(leg.duration.value / 60);
          const km   = (leg.distance.value / 1000).toFixed(1);

          if (el) {{
            const spinner = el.querySelector('.spinner');
            if (spinner) spinner.outerHTML =
              `<div class="route-val done">${{mins}} min · ${{km}} km</div>`;

            if (mode === 'TRANSIT') {{
              const steps = result.routes[0].legs[0].steps
                .filter(s => s.travel_mode === 'TRANSIT')
                .map(s => s.transit?.line?.short_name || s.transit?.line?.name || '')
                .filter(Boolean).join(' → ');
              if (steps) {{
                const sub = el.querySelector('.route-sub');
                if (sub) sub.textContent = steps;
              }}
            }}

            el.onclick = () => {{
              renderers.forEach(r => r.setOptions({{
                polylineOptions:{{ strokeOpacity:0.15, strokeWeight:2 }}
              }}));
              renderer.setOptions({{polylineOptions:{{
                strokeColor:   ROUTE_COLOURS[mode],
                strokeOpacity: 1,
                strokeWeight:  6
              }}}});
              map.fitBounds(result.routes[0].bounds);
            }};
          }}
        }} else {{
          if (el) {{
            const spinner = el.querySelector('.spinner');
            if (spinner) spinner.outerHTML =
              `<div class="route-val" style="color:#64748b">not available</div>`;
          }}
        }}

        if (completed === total) {{
          lb.textContent = '✓ All routes loaded — click a row to highlight';
          lb.style.color = '#22c55e';
        }}
      }});
    }});
  }});
}}
</script>
</body>
</html>"""

output_path = '/content/drive/MyDrive/airport_journey_planner_v7.html'
with open(output_path, 'w') as f:
    f.write(html_content)

print('  Saved: airport_journey_planner_v7.html')

"""comparison between different times at different locations or same -

check how many queries - how much do we have to pay -

find some information about buses or coaches -

straight line distance to the airports -

the other way around as well - from the airport to wherever -

if you do have a point within --ITL3 -- maybe have some center points from where you can get there
"""